
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Nitesh Shewaramani
 */
public class a1 extends javax.swing.JPanel {

    /**
     * Creates new form a1
     */
    public a1() {
        
        initComponents();
        q1.setVisible(true);
        q2.setVisible(false);
        pd.doClick();


        try
        {
        Class.forName("java.sql.Driver");
        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/nbank", "root", "123");
        stmt=con.createStatement();
        String a,b,c,d,e;
        a="delete from ip where class ='" +  "1"   +"'";
        d=" insert into ip values(  curdate() , '" +     "1"  +"'   ) ";
        b="Select * from ip ";
        stmt.executeUpdate(a);
        stmt.executeUpdate(d);
         rs=stmt.executeQuery(b);
        while(rs.next())
         {
        c=rs.getString("date");
        c5.setText("" +c);
       }
            
        }
        catch(Exception ex)
        {

        JOptionPane.showMessageDialog(this, ex.getMessage());
        }



            }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jLabel6 = new javax.swing.JLabel();
        nt2 = new javax.swing.JTextField();
        nt4 = new javax.swing.JTextField();
        nt9 = new javax.swing.JTextField();
        nt7 = new javax.swing.JTextField();
        nt10 = new javax.swing.JTextField();
        nt8 = new javax.swing.JTextField();
        nt3 = new javax.swing.JTextField();
        nt6 = new javax.swing.JTextField();
        nt5 = new javax.swing.JTextField();
        nt1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        q1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        c1 = new javax.swing.JTextField();
        c2 = new javax.swing.JTextField();
        c3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        c6 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        c5 = new javax.swing.JTextField();
        c21 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        q3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ad = new javax.swing.JButton();
        pd = new javax.swing.JButton();
        q2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        c9 = new javax.swing.JTextField();
        c7 = new javax.swing.JTextField();
        c8 = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        c10 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jFrame1.setMinimumSize(new java.awt.Dimension(730, 550));
        jFrame1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 24));
        jLabel6.setText("REVIEW");
        jFrame1.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 110, -1));

        nt2.setFont(new java.awt.Font("Andalus", 1, 18));
        nt2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ACCOUNT NO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Andalus", 1, 14))); // NOI18N
        jFrame1.getContentPane().add(nt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 200, -1));

        nt4.setFont(new java.awt.Font("Andalus", 1, 18));
        nt4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "REGISTRATION NO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Andalus", 1, 14))); // NOI18N
        jFrame1.getContentPane().add(nt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 200, 70));

        nt9.setFont(new java.awt.Font("Andalus", 1, 18));
        nt9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ADDRESS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Andalus", 1, 14))); // NOI18N
        jFrame1.getContentPane().add(nt9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 450, 70));

        nt7.setFont(new java.awt.Font("Andalus", 1, 18));
        nt7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CONTACT NO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Andalus", 1, 14))); // NOI18N
        jFrame1.getContentPane().add(nt7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 200, 70));

        nt10.setFont(new java.awt.Font("Andalus", 1, 18));
        nt10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "E-MAIL", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Andalus", 1, 14))); // NOI18N
        nt10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nt10ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(nt10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 450, 80));

        nt8.setFont(new java.awt.Font("Andalus", 1, 18));
        nt8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ACCOUNT TYPE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Andalus", 1, 14))); // NOI18N
        jFrame1.getContentPane().add(nt8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 200, 70));

        nt3.setFont(new java.awt.Font("Andalus", 1, 18));
        nt3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Andalus", 1, 14))); // NOI18N
        jFrame1.getContentPane().add(nt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, 200, 70));

        nt6.setFont(new java.awt.Font("Andalus", 1, 18));
        nt6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "AMOUNT", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Andalus", 1, 14))); // NOI18N
        jFrame1.getContentPane().add(nt6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 200, 70));

        nt5.setFont(new java.awt.Font("Andalus", 1, 18));
        nt5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "AGE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Andalus", 1, 14))); // NOI18N
        jFrame1.getContentPane().add(nt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 200, 70));

        nt1.setFont(new java.awt.Font("Andalus", 1, 18));
        nt1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "NAME", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Andalus", 1, 14))); // NOI18N
        jFrame1.getContentPane().add(nt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 200, 70));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tick3.jpg"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jFrame1.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 520, 90, 90));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cross2.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jFrame1.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 520, 80, 90));

        setBackground(new java.awt.Color(0, 204, 204));
        setMinimumSize(new java.awt.Dimension(1300, 600));
        setLayout(null);

        q1.setBackground(new java.awt.Color(0, 204, 204));
        q1.setMinimumSize(new java.awt.Dimension(500, 500));
        q1.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Andalus", 1, 24));
        jLabel5.setForeground(new java.awt.Color(102, 0, 102));
        jLabel5.setText("Name");
        q1.add(jLabel5);
        jLabel5.setBounds(70, 80, 70, 40);

        jLabel7.setFont(new java.awt.Font("Andalus", 1, 24));
        jLabel7.setForeground(new java.awt.Color(102, 0, 102));
        jLabel7.setText("Address");
        q1.add(jLabel7);
        jLabel7.setBounds(70, 140, 140, 40);

        jLabel8.setFont(new java.awt.Font("Andalus", 1, 24));
        jLabel8.setForeground(new java.awt.Color(102, 0, 102));
        jLabel8.setText("Contact No.");
        q1.add(jLabel8);
        jLabel8.setBounds(70, 200, 160, 40);
        q1.add(c1);
        c1.setBounds(260, 80, 290, 40);
        q1.add(c2);
        c2.setBounds(260, 140, 290, 40);
        q1.add(c3);
        c3.setBounds(260, 200, 290, 40);

        jLabel4.setFont(new java.awt.Font("Andalus", 0, 48));
        jLabel4.setForeground(new java.awt.Color(102, 0, 102));
        jLabel4.setText("Personal Details");
        q1.add(jLabel4);
        jLabel4.setBounds(470, 0, 400, 70);
        q1.add(c6);
        c6.setBounds(260, 260, 290, 40);

        jLabel3.setFont(new java.awt.Font("Andalus", 1, 24));
        jLabel3.setForeground(new java.awt.Color(102, 0, 102));
        jLabel3.setText("Email Id");
        q1.add(jLabel3);
        jLabel3.setBounds(70, 270, 140, 40);

        jLabel11.setFont(new java.awt.Font("Andalus", 1, 24));
        jLabel11.setForeground(new java.awt.Color(102, 0, 102));
        jLabel11.setText("Date ");
        q1.add(jLabel11);
        jLabel11.setBounds(610, 84, 150, 30);

        jLabel12.setFont(new java.awt.Font("Andalus", 1, 24));
        jLabel12.setForeground(new java.awt.Color(102, 0, 102));
        jLabel12.setText("Age");
        q1.add(jLabel12);
        jLabel12.setBounds(610, 130, 80, 38);
        q1.add(c5);
        c5.setBounds(770, 80, 210, 40);
        q1.add(c21);
        c21.setBounds(770, 130, 210, 40);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/F1.jpg"))); // NOI18N
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        q1.add(jLabel14);
        jLabel14.setBounds(590, 230, 70, 70);

        add(q1);
        q1.setBounds(770, 290, 250, 60);

        q3.setBackground(new java.awt.Color(0, 204, 204));
        q3.setMinimumSize(new java.awt.Dimension(1200, 150));
        q3.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Andalus", 0, 48));
        jLabel2.setForeground(new java.awt.Color(102, 0, 102));
        jLabel2.setText("New Customer");
        q3.add(jLabel2);
        jLabel2.setBounds(430, 0, 350, 89);

        ad.setFont(new java.awt.Font("Andalus", 1, 36));
        ad.setForeground(new java.awt.Color(102, 0, 102));
        ad.setText("Account Details");
        ad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adActionPerformed(evt);
            }
        });
        q3.add(ad);
        ad.setBounds(620, 90, 330, 70);

        pd.setFont(new java.awt.Font("Andalus", 1, 36));
        pd.setForeground(new java.awt.Color(102, 0, 102));
        pd.setText("Personal Details");
        pd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdActionPerformed(evt);
            }
        });
        q3.add(pd);
        pd.setBounds(190, 90, 330, 70);

        add(q3);
        q3.setBounds(50, 0, 1300, 200);

        q2.setBackground(new java.awt.Color(0, 204, 204));
        q2.setMinimumSize(new java.awt.Dimension(800, 550));
        q2.setLayout(null);

        jLabel15.setFont(new java.awt.Font("Andalus", 1, 24));
        jLabel15.setForeground(new java.awt.Color(102, 0, 102));
        jLabel15.setText("Account No.");
        q2.add(jLabel15);
        jLabel15.setBounds(50, 160, 170, 38);

        jLabel16.setFont(new java.awt.Font("Andalus", 0, 48));
        jLabel16.setForeground(new java.awt.Color(102, 0, 102));
        jLabel16.setText("Account Details");
        q2.add(jLabel16);
        jLabel16.setBounds(360, 10, 400, 70);

        jLabel17.setFont(new java.awt.Font("Andalus", 1, 24));
        jLabel17.setForeground(new java.awt.Color(102, 0, 102));
        jLabel17.setText("Registration No.");
        q2.add(jLabel17);
        jLabel17.setBounds(50, 100, 230, 40);

        jLabel18.setFont(new java.awt.Font("Andalus", 1, 24));
        jLabel18.setForeground(new java.awt.Color(102, 0, 102));
        jLabel18.setText("Account type");
        q2.add(jLabel18);
        jLabel18.setBounds(460, 80, 170, 40);
        q2.add(c9);
        c9.setBounds(240, 160, 180, 40);
        q2.add(c7);
        c7.setBounds(240, 100, 180, 40);

        c8.setFont(new java.awt.Font("Andalus", 1, 24));
        c8.setForeground(new java.awt.Color(102, 0, 102));
        c8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Savings Account", "Recurring Deposit", "Fixed Deposit" }));
        q2.add(c8);
        c8.setBounds(460, 120, 350, 40);

        jLabel19.setFont(new java.awt.Font("Andalus", 1, 24));
        jLabel19.setForeground(new java.awt.Color(102, 0, 102));
        jLabel19.setText("Amount");
        q2.add(jLabel19);
        jLabel19.setBounds(50, 220, 130, 38);

        c10.setText("1000");
        q2.add(c10);
        c10.setBounds(240, 230, 180, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FollowUp.jpg"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        q2.add(jLabel1);
        jLabel1.setBounds(460, 170, 170, 160);

        submit.setBackground(new java.awt.Color(0, 0, 0));
        submit.setFont(new java.awt.Font("Andalus", 1, 36));
        submit.setForeground(new java.awt.Color(0, 0, 204));
        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        q2.add(submit);
        submit.setBounds(640, 190, 190, 60);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/B1.jpg"))); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        q2.add(jLabel13);
        jLabel13.setBounds(650, 260, 70, 60);

        add(q2);
        q2.setBounds(760, 400, 230, 80);
    }// </editor-fold>//GEN-END:initComponents
Connection con=null;
Statement stmt =null;
ResultSet rs=null;
    private void adActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adActionPerformed
        // TODO add your handling code here:

        q2.setVisible(true);
        q1.setVisible(false);
        q2.setBounds(50, 200, 1200, 700);

         try
        {
             Class.forName("java.sql.Driver");
             con= DriverManager.getConnection("jdbc:mysql://localhost:3306/nbank","root","123");
             stmt= con.createStatement();
             rs=stmt.executeQuery(" select * from reg where class='"+ 12 +"';");
            while (rs.next())
            {
             String a12 =  rs.getString("regno");
             String a13 =  rs.getString("acno");

              c7.setText("" + a12);
             c9.setText("" + a13);
                     }
        }


         catch (Exception ex)
                {
                    JOptionPane.showMessageDialog(this, ex.getMessage());
                }



     int a21 = Integer.parseInt(c7.getText());
     int   a22 ;
     a22 = a21 + 1;
      int a221 = Integer.parseInt(c9.getText());
     int   a222 ;
   a222 = a221 + 1;


         try

            {
                    Class.forName("java.sql.Driver");
         con= DriverManager.getConnection("jdbc:mysql://localhost:3306/nbank","root","123");
     stmt= con.createStatement();
            String k ="Update reg set regno='"+ a22 +"' ,acno='"+  a222 +"'  where class='" + 12 + "'" ;
           stmt.executeUpdate(k);


            }

        catch (Exception ex)
        {
                    JOptionPane.showMessageDialog(this, ex.getMessage());
                }


         


                
    }//GEN-LAST:event_adActionPerformed

    private void pdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdActionPerformed
        // TODO add your handling code here:

        q1.setVisible(true);
        q2.setVisible(false);
        q1.setBounds(50, 200, 1200, 800);
         
    }//GEN-LAST:event_pdActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
  String a,b;
        a=c1.getText();
        int c11 =a.length();

                if(c11<1)
        {
          JOptionPane.showMessageDialog(this,"pls enter name");

        }
                else
                {
         q2.setVisible(false);
        jFrame1.setVisible(true);
        jFrame1.setBounds(0, 0, 700, 700);
        nt1.setText("" + c1.getText());
        nt2.setText(""+ c9.getText());
        nt3.setText(""+ c5.getText());
        nt4.setText(""+ c7.getText());
        nt5.setText(""+ c21.getText());
        nt6.setText(""+ c10.getText());
        nt7.setText(""+ c3.getText());
        nt8.setText(""+ c8.getSelectedItem());
        nt9.setText(""+ c2.getText());
        nt10.setText(""+ c6.getText());

                }
    }//GEN-LAST:event_submitActionPerformed

    private void nt10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nt10ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_nt10ActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:

        

            int check1 = JOptionPane.showConfirmDialog(null," ARE YOU SURE YOU WANT TO CREATE ACCOUNT  ");
           if(check1 == JOptionPane.YES_OPTION)
           {

            try

            {
                        Class.forName("java.sql.Driver");
            con= DriverManager.getConnection("jdbc:mysql://localhost:3306/nbank","root","123");
           stmt= con.createStatement();
           String nick = "insert into account1 values('"+nt1.getText()+"','"+nt9.getText()+"','"+nt7.getText()+"','"+nt4.getText()+"','"+nt10.getText()+"','"+nt8.getText()+"','"+nt2.getText()+"','"+nt6.getText()+"','"+nt5.getText()+"','"+nt3.getText()+"' ,'" + "On" + "')";

           stmt.executeUpdate(nick);



           JOptionPane.showMessageDialog(this, "Account is created");

             nt1.setText("");
             nt9.setText("");
             nt8.setText("");
             nt7.setText("");
             nt6.setText("");
             nt5.setText("");
             nt4.setText("");
             nt3.setText("");
             nt2.setText("");
             nt10.setText("");

            }

        catch (Exception ex)
        {
                    JOptionPane.showMessageDialog(this, ex.getMessage());
                }
             jFrame1.dispose();
             
                pd.doClick();

                 c1.setText("");  c9.setText("");  c21.setText("");  c3.setText("");  c6.setText("");
            c7.setText("");   c10.setText("1000");   c2.setText("");
           }
        

    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
            q1.setVisible(true);
            q2.setVisible(false);
        
           

            jFrame1.dispose();
            c1.setText("");  c9.setText("");  c21.setText("");  c3.setText("");  c6.setText("");
            c7.setText("");   c10.setText("1000");   c2.setText("");
             pd.doClick();

    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
        pd.doClick();
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
        ad.doClick();

    }//GEN-LAST:event_jLabel14MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ad;
    private javax.swing.JTextField c1;
    private javax.swing.JTextField c10;
    private javax.swing.JTextField c2;
    private javax.swing.JTextField c21;
    private javax.swing.JTextField c3;
    private javax.swing.JTextField c5;
    private javax.swing.JTextField c6;
    private javax.swing.JTextField c7;
    private javax.swing.JComboBox c8;
    private javax.swing.JTextField c9;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nt1;
    private javax.swing.JTextField nt10;
    private javax.swing.JTextField nt2;
    private javax.swing.JTextField nt3;
    private javax.swing.JTextField nt4;
    private javax.swing.JTextField nt5;
    private javax.swing.JTextField nt6;
    private javax.swing.JTextField nt7;
    private javax.swing.JTextField nt8;
    private javax.swing.JTextField nt9;
    private javax.swing.JButton pd;
    private javax.swing.JPanel q1;
    private javax.swing.JPanel q2;
    private javax.swing.JPanel q3;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
