/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nitesh Shewaramani
 */
public class a3 extends javax.swing.JPanel {

    /**
     * Creates new form a3
     */
    public a3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tb1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1400, 900));
        setLayout(null);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Address", "Contact No.", "Registration No.", "Email id", "Account Type", "Account No.", "Amount", "Date", "Age", "Status"
            }
        ));
        jScrollPane1.setViewportView(tb1);

        add(jScrollPane1);
        jScrollPane1.setBounds(0, 290, 1290, 270);

        jLabel2.setFont(new java.awt.Font("Andalus", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 102));
        jLabel2.setText("View  Account");
        add(jLabel2);
        jLabel2.setBounds(500, 20, 490, 89);

        jLabel11.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 0, 102));
        jLabel11.setText("Enter Your Account No.");
        add(jLabel11);
        jLabel11.setBounds(310, 130, 270, 40);
        add(t1);
        t1.setBounds(700, 130, 320, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/index.jpg"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        add(jLabel1);
        jLabel1.setBounds(30, 30, 230, 220);

        jButton6.setFont(new java.awt.Font("Andalus", 1, 36)); // NOI18N
        jButton6.setForeground(new java.awt.Color(102, 0, 102));
        jButton6.setText("View");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        add(jButton6);
        jButton6.setBounds(320, 210, 180, 80);

        jButton7.setFont(new java.awt.Font("Andalus", 1, 36)); // NOI18N
        jButton7.setForeground(new java.awt.Color(102, 0, 102));
        jButton7.setText("Search");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        add(jButton7);
        jButton7.setBounds(530, 210, 180, 80);

        jButton1.setFont(new java.awt.Font("Andalus", 1, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 0, 102));
        jButton1.setText("Empty Table");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(750, 210, 240, 80);
    }// </editor-fold>//GEN-END:initComponents
Connection con=null;
Statement stmt=null;
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        String a,b,c,d,e,f,g,h,i,j,k,l;
         DefaultTableModel t=(DefaultTableModel)tb1.getModel();   
        try
        {   Class.forName("java.sql.Driver");
             con= DriverManager.getConnection("jdbc:mysql://localhost:3306/nbank","root","123");
             stmt= con.createStatement();
            ResultSet rs=stmt.executeQuery(" select * from account1;");

            while (rs.next())
            {
                a=rs.getString("name");
                b=rs.getString("address");
                c=rs.getString("contactno");
                
                e=rs.getString("regno");
                f=rs.getString("email");
                g=rs.getString("acctype");
                h=rs.getString("accno");
                i=rs.getString("amount");
                   j=rs.getString("dob");
                   k=rs.getString("age");
                      l=rs.getString("status");

                  t.addRow(new Object[]{a,b,c,e,f,g,h,i,j,k,l});

            }
             
        }
        catch (Exception ex)
                {
                    JOptionPane.showMessageDialog(this, ex.getMessage());
                }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
         String a,b,c,d,e,f,g,h,i,j,k,l;
                     DefaultTableModel t=(DefaultTableModel)tb1.getModel();
           try
        {      Class.forName("java.sql.Driver");
             con= DriverManager.getConnection("jdbc:mysql://localhost:3306/nbank","root","123");
             stmt= con.createStatement();
            ResultSet rs=stmt.executeQuery(" select * from account1 where accno ='"+t1.getText()+"';");

            while (rs.next())
            {
                a=rs.getString("name");
                b=rs.getString("address");
                c=rs.getString("contactno");
                
                e=rs.getString("regno");
                f=rs.getString("email");
                g=rs.getString("acctype");
                h=rs.getString("accno");
                i=rs.getString("amount");
                j=rs.getString("age");
                k=rs.getString("dob");

   l=rs.getString("status");

                t.addRow(new Object[]{a,b,c,e,f,g,h,i,k,j,l});
                
            }
             
        }
        catch (Exception ex)
                {
                    JOptionPane.showMessageDialog(this, "Error");
                }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel d=(DefaultTableModel)tb1.getModel();
        int r=d.getRowCount();
        if(r>0)
        {
            for(int i=0;i<r;i++)
            {
                d.removeRow(0);
                t1.setText("");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField t1;
    private javax.swing.JTable tb1;
    // End of variables declaration//GEN-END:variables
}
