/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Nitesh
 */
public class casht1 extends javax.swing.JPanel {

    /**
     * Creates new form casht1
     */
    public casht1() {
        initComponents();

        try
        {
        Class.forName("java.sql.Driver");
        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/nbank", "root", "123");
        stmt=con.createStatement();
        String a,b,c,d,e;
        a="delete from ip where class ='" +  "1"   +"'";
        d=" insert into ip values(  curdate() , '" +     "1"  +"'   ) ";
        b="Select * from ip ";
        stmt.executeUpdate(a);
        stmt.executeUpdate(d);
         rs=stmt.executeQuery(b);
        while(rs.next())
         {
        c=rs.getString("date");
        z6.setText("" +c);
       }

        }
        catch(Exception ex)
        {

        JOptionPane.showMessageDialog(this, ex.getMessage());
        }


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        a3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        z5 = new javax.swing.JTextField();
        z1 = new javax.swing.JTextField();
        z2 = new javax.swing.JTextField();
        trans = new javax.swing.JButton();
        z4 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        z6 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        z3 = new javax.swing.JComboBox();

        setMinimumSize(new java.awt.Dimension(1180, 500));
        setPreferredSize(new java.awt.Dimension(1000, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        a3.setBackground(new java.awt.Color(255, 255, 255));
        a3.setLayout(null);

        jLabel18.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 0, 102));
        jLabel18.setText("Amount to be Transfered");
        a3.add(jLabel18);
        jLabel18.setBounds(160, 280, 390, 40);

        jLabel19.setFont(new java.awt.Font("Andalus", 1, 48)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(102, 0, 102));
        jLabel19.setText("Cash Transfer");
        a3.add(jLabel19);
        jLabel19.setBounds(460, 10, 470, 60);

        jLabel20.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(102, 0, 102));
        jLabel20.setText("Account No. of Sender");
        a3.add(jLabel20);
        jLabel20.setBounds(160, 80, 390, 40);

        jLabel21.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(102, 0, 102));
        jLabel21.setText("Registration No. of Sender");
        a3.add(jLabel21);
        jLabel21.setBounds(160, 130, 390, 40);
        a3.add(z5);
        z5.setBounds(550, 280, 360, 40);
        a3.add(z1);
        z1.setBounds(550, 80, 360, 40);
        a3.add(z2);
        z2.setBounds(550, 130, 360, 40);

        trans.setFont(new java.awt.Font("Andalus", 1, 36)); // NOI18N
        trans.setForeground(new java.awt.Color(102, 0, 102));
        trans.setText("Transfer");
        trans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transActionPerformed(evt);
            }
        });
        a3.add(trans);
        trans.setBounds(430, 400, 330, 65);
        a3.add(z4);
        z4.setBounds(550, 230, 360, 40);

        jLabel22.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(102, 0, 102));
        jLabel22.setText("Account No. of Receiver");
        a3.add(jLabel22);
        jLabel22.setBounds(160, 230, 390, 40);

        jLabel25.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(102, 0, 102));
        jLabel25.setText("Date");
        a3.add(jLabel25);
        jLabel25.setBounds(160, 330, 390, 40);
        a3.add(z6);
        z6.setBounds(550, 330, 360, 40);

        jLabel28.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(102, 0, 102));
        jLabel28.setText("Account Type");
        a3.add(jLabel28);
        jLabel28.setBounds(160, 180, 390, 40);

        z3.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        z3.setForeground(new java.awt.Color(102, 0, 102));
        z3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Savings Account", "Recurring Deposit", "Fixed Deposit" }));
        a3.add(z3);
        z3.setBounds(550, 180, 360, 40);

        add(a3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 600));
    }// </editor-fold>//GEN-END:initComponents
Connection con=null;
Statement stmt=null;
ResultSet rs=null;
    private void transActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transActionPerformed
        // TODO add your handling code here:
        String a = null,b = null,c = null, d = null,e = null,f=null;
        int x,y,z,u,v;
                int check1 = JOptionPane.showConfirmDialog(null," ARE YOU SURE YOU WANT TO CONTINUE  ");
        if(check1 == JOptionPane.YES_OPTION)
        {
        try
        {   Class.forName("java.sql.Driver");
             con= DriverManager.getConnection("jdbc:mysql://localhost:3306/nbank","root","123");
             stmt= con.createStatement();
            ResultSet rs=stmt.executeQuery(" select * from account1 where accno = '"+z1.getText()+"';");
            while (rs.next())
            {
                a=rs.getString("regno");
                b=rs.getString("amount");
                f=rs.getString("status");

            }
            ResultSet rs1=stmt.executeQuery(" select * from account1 where accno = '"+z4.getText()+"';");
            while (rs1.next())
            {
                c=rs1.getString("regno");
                d=rs1.getString("amount");
                e=rs1.getString("acctype");
            }
            x=Integer.parseInt(b);
            y=Integer.parseInt(z5.getText());
            z=x-y;
            u=Integer.parseInt(d);
            v=u+y;
            if(a.equals(z2.getText()))
            {
                if(z>0)
                {

                     if(f.equals("On"))
                     {
                    stmt.executeUpdate("insert into stmt1 values('"+z1.getText()+"','"+z2.getText()+"','"+z3.getSelectedItem()+"','"+z5.getText()+"','Transferred','"+z6.getText()+"');");
                    stmt.executeUpdate("insert into stmt1 values('"+z4.getText()+"','"+c+"','"+e+"','"+z5.getText()+"',' Received by Transfer','"+z6.getText()+"');");
                    stmt.executeUpdate("update account1 set amount='"+z+"' where accno='"+z1.getText()+"';");
                    stmt.executeUpdate("update account1 set amount='"+v+"' where accno='"+z4.getText()+"';");
                    JOptionPane.showMessageDialog(this, "Amount is Transfered");
                    z1.setText("");
                    z2.setText("");
                    z4.setText("");
                    z5.setText("");
                     }
                      else
                    {

                    JOptionPane.showMessageDialog(this, "This Account is Blocked");

                      }

                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Amount needed to transfer is more than the amount available in your account");
                }
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Account does not exist");
            }
        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        }
    }//GEN-LAST:event_transActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel a3;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JButton trans;
    private javax.swing.JTextField z1;
    private javax.swing.JTextField z2;
    private javax.swing.JComboBox z3;
    private javax.swing.JTextField z4;
    private javax.swing.JTextField z5;
    private javax.swing.JTextField z6;
    // End of variables declaration//GEN-END:variables
}
