/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nitesh Shewaramani
 */
public class customer1 extends javax.swing.JFrame {

    /**
     * Creates new form customer1
     */
    public customer1() {
        initComponents();

           }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cc1 = new javax.swing.JFrame();
        jLabel6 = new javax.swing.JLabel();
        ca1 = new javax.swing.JLabel();
        ca2 = new javax.swing.JLabel();
        ca3 = new javax.swing.JLabel();
        ca5 = new javax.swing.JLabel();
        ca8 = new javax.swing.JLabel();
        ca9 = new javax.swing.JLabel();
        ca7 = new javax.swing.JLabel();
        ca4 = new javax.swing.JLabel();
        ca11 = new javax.swing.JLabel();
        ca10 = new javax.swing.JLabel();
        ca12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cc2 = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        t11 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        cc1.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        cc1.setMaximizedBounds(new java.awt.Rectangle(0, 0, 800, 496));
        cc1.setMinimumSize(new java.awt.Dimension(800, 496));
        cc1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Traditional Arabic", 1, 36));
        jLabel6.setForeground(new java.awt.Color(0, 204, 204));
        jLabel6.setText("Your Account Details");
        cc1.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 11, 364, -1));

        ca1.setBorder(javax.swing.BorderFactory.createTitledBorder("NAME"));
        cc1.getContentPane().add(ca1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 170, 60));

        ca2.setBorder(javax.swing.BorderFactory.createTitledBorder("ACCOUNT.NO"));
        cc1.getContentPane().add(ca2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 170, 60));

        ca3.setBorder(javax.swing.BorderFactory.createTitledBorder("REGISTRATION.NO"));
        cc1.getContentPane().add(ca3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 170, 60));

        ca5.setBorder(javax.swing.BorderFactory.createTitledBorder("CONTACT.NO"));
        cc1.getContentPane().add(ca5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 170, 60));

        ca8.setBorder(javax.swing.BorderFactory.createTitledBorder("ACCOUNT TYPE"));
        cc1.getContentPane().add(ca8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 170, 60));

        ca9.setBorder(javax.swing.BorderFactory.createTitledBorder("BALANCE"));
        cc1.getContentPane().add(ca9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, 170, 60));

        ca7.setBorder(javax.swing.BorderFactory.createTitledBorder("E-MAIL"));
        cc1.getContentPane().add(ca7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 420, 60));

        ca4.setBorder(javax.swing.BorderFactory.createTitledBorder("ADDRESS"));
        cc1.getContentPane().add(ca4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 420, 60));

        ca11.setBorder(javax.swing.BorderFactory.createTitledBorder("AGE"));
        cc1.getContentPane().add(ca11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 130, 60));

        ca10.setBorder(javax.swing.BorderFactory.createTitledBorder("AGE"));
        cc1.getContentPane().add(ca10, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, 130, 60));

        ca12.setBorder(javax.swing.BorderFactory.createTitledBorder("STATUS"));
        cc1.getContentPane().add(ca12, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 130, 60));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ip23.jpg"))); // NOI18N
        cc1.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 480));

        cc2.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        cc2.setMinimumSize(new java.awt.Dimension(800, 400));
        cc2.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Account No.", "Registration No.", "Account type", "Amount", "Trasnsaction Type", "Date"
            }
        ));
        jScrollPane1.setViewportView(tb1);

        cc2.getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 840, 310));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel4.setText("Account Statement");
        cc2.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 350, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ip23.jpg"))); // NOI18N
        cc2.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 410));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Andalus", 1, 36));
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setText("View Account statement & Account");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 4, 610, 50));

        jLabel2.setFont(new java.awt.Font("Andalus", 1, 36));
        jLabel2.setForeground(new java.awt.Color(102, 0, 102));
        jLabel2.setText("Enter your account no");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        t11.setFont(new java.awt.Font("Andalus", 1, 18));
        t11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t11ActionPerformed(evt);
            }
        });
        getContentPane().add(t11, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 240, 40));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Andalus", 1, 36));
        jButton1.setForeground(new java.awt.Color(0, 153, 153));
        jButton1.setText("Show Account Details");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 440, -1));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 36));
        jButton2.setForeground(new java.awt.Color(204, 0, 51));
        jButton2.setText("Show Statements");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, -1, 70));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yellow.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents
Connection con=null;
Statement stmt=null;
ResultSet rs=null;
private void t11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t11ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_t11ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
cc2.setVisible(true);
cc2.setBounds(0, 0, 600, 400);
       String a,b,c,d,e,f;
                    DefaultTableModel t=(DefaultTableModel)tb1.getModel();
          
                    
                    
        int r=t.getRowCount();
        if(r>0)
        {
            for(int i=0;i<r;i++)
            {
                t.removeRow(0);
               
            }
        
                    
                    
              try
        {


               Class.forName("java.sql.Driver");
            con= DriverManager.getConnection("jdbc:mysql://localhost:3306/nbank","root","123");
             stmt= con.createStatement();
             rs=stmt.executeQuery(" select * from stmt1 where accno='"+t11.getText()+"';");

            while (rs.next())
            {
                a=rs.getString("accno");
                b=rs.getString("regno");
                c=rs.getString("acctype");
                d=rs.getString("amount");
                e=rs.getString("transfer");
                f=rs.getString("date");
                    t.addRow(new Object[]{a,b,c,d,e,f});
            }

        }
        catch (Exception ex)
                {
                    JOptionPane.showMessageDialog(this, ex.getMessage());
                }

        }


        else
        {



              try
        {


               Class.forName("java.sql.Driver");
            con= DriverManager.getConnection("jdbc:mysql://localhost:3306/nbank","root","123");
             stmt= con.createStatement();
             rs=stmt.executeQuery(" select * from stmt1 where accno='"+t11.getText()+"';");

            while (rs.next())
            {
                a=rs.getString("accno");
                b=rs.getString("regno");
                c=rs.getString("acctype");
                d=rs.getString("amount");
                e=rs.getString("transfer");
                f=rs.getString("date");
                    t.addRow(new Object[]{a,b,c,d,e,f});
            }

        }
        catch (Exception ex)
                {
                    JOptionPane.showMessageDialog(this, ex.getMessage());
                }


        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        cc1.setVisible(true);
        cc1.setBounds(0, 0, 600, 496);
                    
        try
        {
        Class.forName("java.sql.Driver");
        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/nbank","root","123");
        stmt=con.createStatement();
         rs=stmt.executeQuery(" select * from account1 where accno='"+t11.getText()+"';");
         while(rs.next())
         {
         ca1.setText(""+rs.getString("name"));
         ca2.setText(""+rs.getString("accno"));
         ca3.setText(""+rs.getString("regno"));
         ca4.setText(""+rs.getString("address"));
         ca5.setText(""+rs.getString("contactno"));
         ca11.setText(""+rs.getString("accno"));
         ca7.setText(""+rs.getString("email"));
         ca8.setText(""+rs.getString("acctype"));
         ca9.setText(""+rs.getString("amount"));
         ca10.setText(""+rs.getString("dob"));

         ca12.setText(""+rs.getString("STATUS"));
         }



        }
        catch(Exception ex)
        {
        JOptionPane.showMessageDialog(this, ex.getMessage());
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(customer1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(customer1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(customer1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(customer1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new customer1().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ca1;
    private javax.swing.JLabel ca10;
    private javax.swing.JLabel ca11;
    private javax.swing.JLabel ca12;
    private javax.swing.JLabel ca2;
    private javax.swing.JLabel ca3;
    private javax.swing.JLabel ca4;
    private javax.swing.JLabel ca5;
    private javax.swing.JLabel ca7;
    private javax.swing.JLabel ca8;
    private javax.swing.JLabel ca9;
    private javax.swing.JFrame cc1;
    private javax.swing.JFrame cc2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField t11;
    private javax.swing.JTable tb1;
    // End of variables declaration//GEN-END:variables
}
