/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * last.java
 *
 * Created on 9 Dec, 2014, 5:44:57 AM
 */



import java.sql.*;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.sql.Statement;



class stoptimer1
{
    static Timer t;
    public static void send(ActionListener e)
    {
         t= new Timer(200,e);
        t.start();
    }
    public static void stopt()
    {
        t.stop();
            }
}

/**
 *
 * @author Nitesh Shewaramani
 */
public class last extends javax.swing.JFrame {

    /** Creates new form last */
    public last() {
        initComponents();
        jd2.doClick();
                                   int g= 0;
            g=g*1000;
       ActionListener b=new ActionListener()
       {
          public void actionPerformed(ActionEvent e) {

             h++;
       if(h==1)
       {       l1.setForeground(Color.red);         }
           if(h==2)
       {       l2.setForeground(Color.red);         }
           if(h==3)
       {       l3.setForeground(Color.red);         }
           if(h==4)
       {       l4.setForeground(Color.red);         }
       if(h==5)
       {       l5.setForeground(Color.red);         }
           if(h==6)
       {       l6.setForeground(Color.red);         }
           if(h==7)
       {       l7.setForeground(Color.red);         }
           if(h==8)
       {       l8.setForeground(Color.red);}
       if(h==9)
       {       l9.setForeground(Color.WHITE);}
       if(h==10)
       {       l8.setForeground(Color.WHITE);}
       if(h==11)
       {       l7.setForeground(Color.WHITE);}
       if(h==12)
       {       l6.setForeground(Color.WHITE);}
       if(h==13)
       {       l5.setForeground(Color.WHITE);}
       if(h==14)
       {       l4.setForeground(Color.WHITE);
       }

       if(h==15)
       {       l3.setForeground(Color.WHITE);         }
           if(h==16)
       {       l2.setForeground(Color.WHITE);         }
           if(h==17)
       {       l1.setForeground(Color.WHITE);
       h=0;}



          }

       };

         stoptimer1.send(b);





    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd2 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        l8 = new javax.swing.JLabel();
        l9 = new javax.swing.JLabel();
        l6 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        l7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jd2.setText("jButton3");
        jd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jd2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("WELCOME TO CITIZENS BANK OF INDIA");
        setMinimumSize(new java.awt.Dimension(955, 570));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Segoe Print", 1, 24));
        jLabel16.setText("CLASS 12th - SCIENCE");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, 330, -1));

        l4.setFont(new java.awt.Font("Segoe Print", 1, 24));
        l4.setText("A");
        getContentPane().add(l4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 30, -1));

        jLabel13.setFont(new java.awt.Font("Segoe Print", 1, 24));
        jLabel13.setText("AAYUSH SRIVASTAV");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 280, -1));

        l2.setFont(new java.awt.Font("Segoe Print", 1, 24));
        l2.setText("R");
        getContentPane().add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 30, -1));

        l5.setFont(new java.awt.Font("Segoe Print", 1, 24));
        l5.setText("T");
        getContentPane().add(l5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 30, -1));

        jLabel11.setFont(new java.awt.Font("Segoe Print", 1, 24));
        jLabel11.setText("NITESH SHEWARAMANI");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 214, 320, 40));

        jLabel10.setFont(new java.awt.Font("Segoe Print", 1, 24));
        jLabel10.setText("BHARAT RAMNANI");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 270, -1));

        l8.setFont(new java.awt.Font("Segoe Print", 1, 24));
        l8.setText("B");
        getContentPane().add(l8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 30, -1));

        l9.setFont(new java.awt.Font("Segoe Print", 1, 24));
        l9.setText("Y");
        getContentPane().add(l9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 30, -1));

        l6.setFont(new java.awt.Font("Segoe Print", 1, 24));
        l6.setText("E");
        getContentPane().add(l6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 30, -1));

        l3.setFont(new java.awt.Font("Segoe Print", 1, 24));
        l3.setText("E");
        getContentPane().add(l3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 30, -1));

        l1.setFont(new java.awt.Font("Segoe Print", 1, 24));
        l1.setText("C");
        getContentPane().add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 30, -1));

        l7.setFont(new java.awt.Font("Segoe Print", 1, 24));
        l7.setText("D");
        getContentPane().add(l7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 30, -1));

        jLabel14.setFont(new java.awt.Font("Segoe Print", 1, 24));
        jLabel14.setText("SUBMITTED TO -");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, 280, -1));

        jLabel15.setFont(new java.awt.Font("Segoe Print", 1, 24));
        jLabel15.setText("DEVANDRA SHARMA SIR");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, 330, -1));

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 24));
        jLabel1.setText("SESSION :- 2014-2015");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, 330, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/log3.jpg"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 230, 70));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/x.gif"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, 90, 130));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ip81.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents
  int t,t2,n=0;
    Connection con =null;
    Statement stmt=null;
    ResultSet rs=null;
   int h=0;
    boolean check =true,check1=false;


    private void jd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jd2ActionPerformed
        // TODO add your handling code here:
    String a,b,c,d;
             try {
            Class.forName("java.sql.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/nbank", "root", "123");
            stmt = con.createStatement();
            String dd1 = "use nbank;";
            stmt.executeUpdate(dd1);
}
        catch(ClassNotFoundException ex1) {
            check=false;
        } catch (SQLException ex1) {
            check=false;
        }
        if(check==false) {
            try{
                Class.forName("java.sql.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/", "root", "123");
                stmt = con.createStatement();
                d = "create database nbank;";
                stmt.execute(d);
                c="use nbank;";
                stmt.execute(c);
                b=" create table account1(name varchar(50),address varchar(100),contactno varchar(15),regno varchar(4),email varchar(150),acctype varchar(20),accno varchar(4),amount varchar(30),age  varchar(3),dob varchar(16),status varchar(3))";
                stmt.execute(b);
                String x="create table stmt1(accno varchar(4),regno varchar(4),acctype varchar(50),amount varchar(35),transfer varchar(30),date varchar(16))";
                stmt.execute(x);
                String y="   create table reg(acno varchar(12),regno varchar(12),class varchar(3));   ";
                stmt.execute(y);
                String z="  create table pas(name varchar(12),password varchar(30),hint varchar(100)); ";
                stmt.execute(z);
                 String z1="  create table ip(date date,class varchar(2)); ";
                stmt.execute(z1);
                String u=" insert into reg values('3','303','12') ;";
                String u1=" insert into pas values('admin','9301514025','no.enohp'  ) ;";
                String u2=" insert into pas values('user','nitesh','name') ;";
                String u3=" insert into account1 values('Ravi','B-9 panchvaty ,bhopal','9098069954','301','ravi@yahoo.com','Savings account','1','10000','32','2014-12-13','On')   ;";
                String u4=" insert into account1 values('Rahul','B-2 panchvaty ,bhopal','9039455350','302','rahul@yahoo.com','Savings account','2','10000','33','2014-12-13','On')   ;";
                String u5=" insert into stmt1 values('1','301','Savings account','1000','deposit','2014-12-13')   ;";
                String u6 =" insert into stmt1 values('2','302','Savings account','1000','deposit','2014-12-13')   ;";
                System.out.println("done");
                stmt.executeUpdate(u3);
                stmt.executeUpdate(u4);
                stmt.executeUpdate(u2);
                stmt.executeUpdate(u);
                stmt.executeUpdate(u1);
                stmt.executeUpdate(u5);
                stmt.executeUpdate(u6);
System.out.println("done");


            } catch(Exception ex) {

                JOptionPane.showMessageDialog(null, ex.getMessage());
            }}


    }//GEN-LAST:event_jd2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new niteshlog().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new last().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jd2;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    private javax.swing.JLabel l7;
    private javax.swing.JLabel l8;
    private javax.swing.JLabel l9;
    // End of variables declaration//GEN-END:variables

}
