/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * niteshviewac.java
 *
 * Created on 17 Dec, 2014, 7:26:44 AM
 */
import java.awt.Color;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Nitesh Shewaramani
 */
public class niteshviewac extends javax.swing.JFrame {

    /** Creates new form niteshviewac */
    public niteshviewac() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        t6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        reg = new javax.swing.JLabel();
        age = new javax.swing.JLabel();
        bal = new javax.swing.JLabel();
        acc = new javax.swing.JLabel();
        cont = new javax.swing.JLabel();
        ema = new javax.swing.JLabel();
        add = new javax.swing.JLabel();
        dat = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Andalus", 0, 48)); // NOI18N
        jLabel14.setText("View  Account");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, -1, -1));

        jLabel15.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        jLabel15.setText("Enter Your Account No.");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));
        getContentPane().add(t6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 160, 40));

        jButton1.setText("SEARCH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 130, 100, 50));

        reg.setBorder(javax.swing.BorderFactory.createTitledBorder("REG.NO"));
        getContentPane().add(reg, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 190, 50));

        age.setBorder(javax.swing.BorderFactory.createTitledBorder("AGE"));
        getContentPane().add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, 190, 50));

        bal.setBorder(javax.swing.BorderFactory.createTitledBorder("BALANCE"));
        getContentPane().add(bal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 190, 60));

        acc.setBorder(javax.swing.BorderFactory.createTitledBorder("ACCOUNT TYPE"));
        getContentPane().add(acc, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 190, 60));

        cont.setBorder(javax.swing.BorderFactory.createTitledBorder("CONTACT.NO"));
        getContentPane().add(cont, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, 190, 50));

        ema.setBorder(javax.swing.BorderFactory.createTitledBorder("EMAIL"));
        getContentPane().add(ema, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 190, 60));

        add.setBorder(javax.swing.BorderFactory.createTitledBorder("ADDRESS"));
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 410, 60));

        dat.setBorder(javax.swing.BorderFactory.createTitledBorder("DATE"));
        getContentPane().add(dat, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 190, 60));

        name.setBorder(javax.swing.BorderFactory.createTitledBorder("NAME"));
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 190, 50));

        jButton2.setText("CLEAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 120, 50));

        jButton3.setText("BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, 100, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents
Connection con=null;
Statement stmt=null;
ResultSet rs=null;

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        String a,b,c,d,e,f,g,h,i,j,k;

        try {
            Class.forName("java.sql.Driver");
            con= DriverManager.getConnection("jdbc:mysql://localhost:3306/nbank","root","123");
            stmt= con.createStatement();
            rs=stmt.executeQuery(" select * from account1 where accno = '"+t6.getText()+"';");

            while (rs.next()) {
                a=rs.getString("name");
                b=rs.getString("address");
                c=rs.getString("contactno");
                e=rs.getString("regno");
                f=rs.getString("email");
                g=rs.getString("acctype");
                h=rs.getString("accno");
                i=rs.getString("amount");
                j=rs.getString("age");
                k=rs.getString("dob");
               name.setText(""+a);
               reg.setText("" +e);
               age.setText("" + j);
               bal.setText("" +i);
               acc.setText("" + g);
               cont.setText("" +c);
               ema.setText("" +f);
               dat.setText("" + k);
               add.setText("" +b);



            }


        }

        catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         name.setText("");
               reg.setText("");
               age.setText("" );
               bal.setText("" );
               acc.setText("" );
               cont.setText("");
               ema.setText("" );
               dat.setText("" );
               add.setText("" );
               t6.setText("");

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new niteshuser().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed
  
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new niteshviewac().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel acc;
    private javax.swing.JLabel add;
    private javax.swing.JLabel age;
    private javax.swing.JLabel bal;
    private javax.swing.JLabel cont;
    private javax.swing.JLabel dat;
    private javax.swing.JLabel ema;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel name;
    private javax.swing.JLabel reg;
    private javax.swing.JTextField t6;
    // End of variables declaration//GEN-END:variables

}
