import java.awt.Color;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * niteshviewstmt.java
 *
 * Created on 17 Dec, 2014, 7:27:03 AM
 */

/**
 *
 * @author Nitesh Shewaramani
 */
public class niteshviewstmt extends javax.swing.JFrame {

    /** Creates new form niteshviewstmt */
    public niteshviewstmt() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        t7 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb2 = new javax.swing.JTable();
        jLabel38 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel59 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1120, 590));
        getContentPane().setLayout(null);

        jLabel36.setFont(new java.awt.Font("Andalus", 0, 48)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(102, 0, 102));
        jLabel36.setText("View  Account Statement");
        getContentPane().add(jLabel36);
        jLabel36.setBounds(480, 20, 710, 89);

        jLabel37.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(102, 0, 102));
        jLabel37.setText("Enter Your Account No.");
        getContentPane().add(jLabel37);
        jLabel37.setBounds(380, 140, 310, 40);
        getContentPane().add(t7);
        t7.setBounds(770, 140, 330, 40);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tb2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Account No.", "Registration No.", "Account type", "Amount", "Trasnsaction Type", "Date"
            }
        ));
        jScrollPane2.setViewportView(tb2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(0, 320, 1100, 250);

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/2.jpg"))); // NOI18N
        jLabel38.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        getContentPane().add(jLabel38);
        jLabel38.setBounds(10, 60, 290, 190);

        jButton9.setFont(new java.awt.Font("Andalus", 1, 36)); // NOI18N
        jButton9.setForeground(new java.awt.Color(102, 0, 102));
        jButton9.setText("Search");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(470, 230, 210, 80);

        jButton2.setFont(new java.awt.Font("Andalus", 1, 36)); // NOI18N
        jButton2.setForeground(new java.awt.Color(102, 0, 102));
        jButton2.setText("Empty Table");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(740, 230, 270, 80);

        jLabel59.setIcon(new javax.swing.ImageIcon(getClass().getResource("/B1.jpg"))); // NOI18N
        jLabel59.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel59MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel59);
        jLabel59.setBounds(370, 240, 70, 60);

        pack();
    }// </editor-fold>//GEN-END:initComponents
Connection con=null;
Statement stmt=null;
ResultSet rs=null;
    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        String a,b,c,d,e,f;
        DefaultTableModel t100=(DefaultTableModel)tb2.getModel();
        try {
            Class.forName("java.sql.Driver");
            con= DriverManager.getConnection("jdbc:mysql://localhost:3306/nbank","root","123");
            stmt= con.createStatement();
            rs=stmt.executeQuery(" select * from stmt1 where accno = '" + t7.getText()+ " ' ; ");

            while (rs.next()) {
                a=rs.getString("accno");
                b=rs.getString("regno");
                c=rs.getString("acctype");
                d=rs.getString("amount");
                e=rs.getString("transfer");
                f=rs.getString("date");
                t100.addRow(new Object[]{a,b,c,d,e,f});

            }

        }


        catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }

    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel d=(DefaultTableModel)tb2.getModel();
        int r=d.getRowCount();
        if(r>0) {
            for(int i=0;i<r;i++) {
                d.removeRow(0);
                t7.setText("");
            }
        }
}//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel59MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel59MouseClicked
        // TODO add your handling code here:
        new niteshuser().setVisible(true);
        this.setVisible(false);
}//GEN-LAST:event_jLabel59MouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new niteshviewstmt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField t7;
    private javax.swing.JTable tb2;
    // End of variables declaration//GEN-END:variables

}
