/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.Color;
/**
 *
 * @author Nitesh Shewaramani
 */
public class niteshad1 extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public niteshad1() {
        initComponents();
         m1.setVisible(true);
           this.getContentPane().setBackground(Color.CYAN);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        changepas = new javax.swing.JFrame();
        pw1 = new javax.swing.JPasswordField();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        pw3 = new javax.swing.JPasswordField();
        pw2 = new javax.swing.JPasswordField();
        cb1 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        hint = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jFrame2 = new javax.swing.JFrame();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        update = new javax.swing.JFrame();
        jLabel10 = new javax.swing.JLabel();
        p1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        p2 = new javax.swing.JTextField();
        jp1 = new javax.swing.JPanel();
        nc5 = new javax.swing.JTextField();
        nc4 = new javax.swing.JTextField();
        nc1 = new javax.swing.JTextField();
        nc2 = new javax.swing.JTextField();
        nc3 = new javax.swing.JTextField();
        nc6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        delstmt = new javax.swing.JFrame();
        t2 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb2 = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        m1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        changepas.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        changepas.setMinimumSize(new java.awt.Dimension(700, 500));
        changepas.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pw1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pw1.setForeground(new java.awt.Color(102, 0, 102));
        pw1.setToolTipText("ENTER CURRENT PASSWORD");
        pw1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ENTER TOUR CURRENT PASSWORD", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 12))); // NOI18N
        changepas.getContentPane().add(pw1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 220, 80));

        jButton4.setFont(new java.awt.Font("Vijaya", 1, 36)); // NOI18N
        jButton4.setForeground(new java.awt.Color(102, 0, 102));
        jButton4.setText("CANCEL");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        changepas.getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, 180, -1));

        jButton3.setFont(new java.awt.Font("Vijaya", 1, 36)); // NOI18N
        jButton3.setForeground(new java.awt.Color(102, 0, 102));
        jButton3.setText("CHANGE PASSWORD");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        changepas.getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        pw3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pw3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CONFORM NEW PASSWORD", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 12))); // NOI18N
        changepas.getContentPane().add(pw3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 180, 80));

        pw2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pw2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ENTER NEW PASSWORD", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 12))); // NOI18N
        changepas.getContentPane().add(pw2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 190, 80));

        cb1.setFont(new java.awt.Font("Vijaya", 1, 24)); // NOI18N
        cb1.setForeground(new java.awt.Color(102, 0, 102));
        cb1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "admin", "user" }));
        changepas.getContentPane().add(cb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 110, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 102));
        jLabel5.setText("Change Password for");
        changepas.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 210, -1));

        hint.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TYPE YOUR HINT", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 14))); // NOI18N
        changepas.getContentPane().add(hint, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 640, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ip23.jpg"))); // NOI18N
        changepas.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 580));

        jFrame2.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jFrame2.setBackground(new java.awt.Color(255, 255, 255));
        jFrame2.setMinimumSize(new java.awt.Dimension(800, 500));
        jFrame2.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/del2.jpg"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jFrame2.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, 250, 80));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/up1.jpg"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jFrame2.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 240, 160));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/log5.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jFrame2.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 380, 220, 80));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/B1.jpg"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jFrame2.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, 60));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgb8.png"))); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        jFrame2.getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 180, 170));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/del2.jpg"))); // NOI18N
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        jFrame2.getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 250, 80));

        jLabel22.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel22.setText("Delete Statement");
        jFrame2.getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, -1, -1));

        jLabel23.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel23.setText("Delete Account");
        jFrame2.getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, -1, -1));

        update.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        update.setBackground(new java.awt.Color(0, 255, 255));
        update.setMinimumSize(new java.awt.Dimension(1000, 590));
        update.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                updateWindowOpened(evt);
            }
        });
        update.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Andalus", 0, 48)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 0, 102));
        jLabel10.setText("Update");
        update.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 4, 194, 51));

        p1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                p1FocusLost(evt);
            }
        });
        update.getContentPane().add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 140, 40));

        jLabel17.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 0, 102));
        jLabel17.setText("Registration No.");
        update.getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 186, 40));

        jLabel15.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 0, 102));
        jLabel15.setText("Account No.");
        jLabel15.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel15KeyPressed(evt);
            }
        });
        update.getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 140, -1));

        p2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                p2KeyPressed(evt);
            }
        });
        update.getContentPane().add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, 130, 40));

        jp1.setBackground(new java.awt.Color(0, 255, 255));
        jp1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nc5.setFont(new java.awt.Font("Neuropol", 1, 14)); // NOI18N
        nc5.setToolTipText("ENTER YOUR CONTACT NUMBER");
        nc5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CONTACT NUMBER", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Neuropol", 0, 10))); // NOI18N
        jp1.add(nc5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 240, -1));

        nc4.setFont(new java.awt.Font("Neuropol", 1, 14)); // NOI18N
        nc4.setToolTipText("ENTER YOUR CONTACT NUMBER");
        nc4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "AGE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Neuropol", 0, 10))); // NOI18N
        jp1.add(nc4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 240, -1));

        nc1.setFont(new java.awt.Font("Neuropol", 1, 14)); // NOI18N
        nc1.setToolTipText("ENTER YOUR CONTACT NUMBER");
        nc1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ADDRESS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Neuropol", 0, 10))); // NOI18N
        jp1.add(nc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 360, -1));

        nc2.setFont(new java.awt.Font("Neuropol", 1, 14)); // NOI18N
        nc2.setToolTipText("ENTER YOUR EMAIL ADDRESS");
        nc2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "E-MAIL", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Neuropol", 0, 10))); // NOI18N
        jp1.add(nc2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 284, -1));

        nc3.setFont(new java.awt.Font("Neuropol", 1, 14)); // NOI18N
        nc3.setToolTipText("");
        nc3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "STATUS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Neuropol", 0, 10))); // NOI18N
        jp1.add(nc3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 290, -1));

        nc6.setFont(new java.awt.Font("Neuropol", 1, 14)); // NOI18N
        nc6.setToolTipText("ENTER YOUR CONTACT NUMBER");
        nc6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "NAME", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Neuropol", 0, 10))); // NOI18N
        jp1.add(nc6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 290, -1));

        jButton1.setBackground(new java.awt.Color(51, 51, 255));
        jButton1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jp1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 160, 60));

        update.getContentPane().add(jp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 1100, 390));

        jButton2.setBackground(new java.awt.Color(51, 255, 0));
        jButton2.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jButton2.setText("SHOW DETAILS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        update.getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 70, -1, 50));

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 0));
        jButton5.setText("BACK");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        update.getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 130, 160, 50));

        delstmt.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        delstmt.setBackground(new java.awt.Color(255, 255, 255));
        delstmt.setMaximizedBounds(new java.awt.Rectangle(0, 0, 900, 500));
        delstmt.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        t2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t2KeyPressed(evt);
            }
        });
        delstmt.getContentPane().add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 250, 40));

        jLabel18.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 0, 102));
        jLabel18.setText("Enter Your Account No.");
        delstmt.getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 272, 40));

        jButton6.setFont(new java.awt.Font("Andalus", 1, 36)); // NOI18N
        jButton6.setForeground(new java.awt.Color(102, 0, 102));
        jButton6.setText("Delete");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        delstmt.getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, 180, 50));

        tb2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Account No.", "Registration No.", "Account type", "Amount", "Trasnsaction Type", "Date"
            }
        ));
        jScrollPane2.setViewportView(tb2);

        delstmt.getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 810, 180));

        jLabel19.setFont(new java.awt.Font("Andalus", 0, 48)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(102, 0, 102));
        jLabel19.setText("Delete  Account Statement");
        delstmt.getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 540, 60));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/B1.jpg"))); // NOI18N
        jLabel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel26MouseClicked(evt);
            }
        });
        delstmt.getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, 60));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 570));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 2, 48)); // NOI18N
        jLabel1.setText("Welcome to State Bank of India");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 20, 740, 89);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/settings1.jpg"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(680, 370, 250, 90);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ip45.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, -410, 1030, 930);

        jMenu1.setForeground(new java.awt.Color(102, 0, 102));
        jMenu1.setText("File");
        jMenu1.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jMenuItem1.setForeground(new java.awt.Color(102, 0, 102));
        jMenuItem1.setText("New Customer");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem4.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jMenuItem4.setForeground(new java.awt.Color(102, 0, 102));
        jMenuItem4.setText("Cash deposit");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem3.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jMenuItem3.setForeground(new java.awt.Color(102, 0, 102));
        jMenuItem3.setText("Cash Withdrawal");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem9.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jMenuItem9.setForeground(new java.awt.Color(102, 0, 102));
        jMenuItem9.setText("Settings");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem9);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem7.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jMenuItem7.setForeground(new java.awt.Color(102, 0, 102));
        jMenuItem7.setText("Cash Transfer");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        m1.add(jMenu1);

        jMenu3.setForeground(new java.awt.Color(102, 0, 102));
        jMenu3.setText("View");
        jMenu3.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem5.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jMenuItem5.setForeground(new java.awt.Color(102, 0, 102));
        jMenuItem5.setText("View account");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem8.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jMenuItem8.setForeground(new java.awt.Color(102, 0, 102));
        jMenuItem8.setText("View Statement");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem8);

        m1.add(jMenu3);

        jMenu2.setForeground(new java.awt.Color(102, 0, 102));
        jMenu2.setText("Exit");
        jMenu2.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem6.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jMenuItem6.setForeground(new java.awt.Color(102, 0, 102));
        jMenuItem6.setText("Exit");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem2.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jMenuItem2.setForeground(new java.awt.Color(102, 0, 102));
        jMenuItem2.setText("Log out");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        m1.add(jMenu2);

        setJMenuBar(m1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
 Connection con =null;
 ResultSet  rs= null ;
 Statement stmt=null;
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
       niteshad1 f=new niteshad1();
        f.setContentPane(new a1());
        f.setBounds(0, 0, 1300, 600);
        f.show();
     
         
          m1.setVisible(false);
         this.setVisible(false);


    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:

        new last().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
           this.setVisible(false);
        m1.setVisible(true);
        
        niteshlog h1 = new niteshlog();
         h1.setVisible(true);
           
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
               niteshad1 f=new niteshad1();
        f.setContentPane(new casht1());
        f.setBounds(0, 0, 800, 450);
        f.show();
        this.setVisible(false);
        m1.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
               niteshad1 f=new niteshad1();
        f.setContentPane(new cashw1());
        f.setBounds(0, 0, 800, 450);
        f.show();
        
        
        m1.setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
               niteshad1 f=new niteshad1();
        f.setContentPane(new cashd1());
        f.setBounds(0, 0, 800, 450);
        f.show();

              m1.setVisible(true); 
         
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        niteshad1 f=new niteshad1();

        f.setContentPane(new a3());
        f.setBounds(0, 0, 1300, 700);
        f.show();
         
         this.setVisible(false);
                 m1.setVisible(false);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        niteshad1 f=new niteshad1();

        f.setContentPane(new a4());
        f.setBounds(0, 0, 1100, 700);
        f.show();
          m1.setVisible(false);
         
         this.setVisible(false);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String p = null ;
        String p1 = new String(pw1.getPassword());
      int check1 = JOptionPane.showConfirmDialog(null," ARE YOU SURE YOU WANT TO CHANGE PASSWORD ");
           if(check1 == JOptionPane.YES_OPTION)
           {
        try
        {     Class.forName("java.sql.Driver");
             con=DriverManager.getConnection("jdbc:mysql://localhost:3306/nbank","root","123");
             stmt= con.createStatement();
            ResultSet rs=stmt.executeQuery(" select * from pas  where name = '" + cb1.getSelectedItem() + "';");
            while(rs.next())
            {
            p=rs.getString("password");
            
            }
            if(p.equals(p1))
            {
             String p2=new String(pw2.getPassword());
                    String p3=new String(pw3.getPassword());
            if(p2.equals(p3))
            {
                    try
        {
             con=DriverManager.getConnection("jdbc:mysql://localhost:3306/nbank","root","123");
             stmt= con.createStatement();
             String k ="Update pas set password='"+ p2 +"' ,hint =' " + hint.getText() + " '  where name='" + cb1.getSelectedItem() + "'" ;
           stmt.executeUpdate(k);

             
                
            }
                    
                    
                    
                    
                  catch (Exception ex)
                {
                    JOptionPane.showMessageDialog(this, ex.getMessage());
                }  
                    
                    
            }
            
            else
            {
                    JOptionPane.showMessageDialog(this, "NEW PASSWORDS DO NOT MATCH");
                    pw2.setText("");
                       pw3.setText("");
            }
            
        }
            else
            {
                    JOptionPane.showMessageDialog(this, "INCORRECT PASSWORD");
            }
        }
        
        catch (Exception ex)
                {
                    JOptionPane.showMessageDialog(this, ex.getMessage());
                }

      hint.setText("");
      pw1.setText("");
      pw2.setText("");
      pw3.setText("");


    }


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:

        niteshad1 m11 = new niteshad1();
               m11.setVisible(true);
            changepas.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        jFrame2.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jLabel3MouseClicked

    private void p1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_p1FocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_p1FocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int check1 = JOptionPane.showConfirmDialog(null," ARE YOU SURE YOU WANT TO CONTINUE      ");
        if(check1 == JOptionPane.YES_OPTION) {

            try

            {
                Class.forName("java.sql.Driver");
                con= DriverManager.getConnection("jdbc:mysql://localhost:3306/nbank","root","123");
                stmt= con.createStatement();
                System.out.println("done1");
                String nick = "Update account1 set address = '" + nc1.getText() +"', email = '" +nc2.getText()+ "' , contactno = '"+nc5.getText()+"', age = '"+nc4.getText()+"', name = '"+nc6.getText()+"', status = '"+nc3.getText()+"' ,dob=curdate()   where regno='"+p1.getText()+"' ;";
                stmt.executeUpdate(nick);
                   System.out.println("done");
                JOptionPane.showMessageDialog(this, "Account is Updated");

                jp1.setVisible(false);
                nc1.setText("");
                nc2.setText("");
           
                nc4.setText("");
                nc5.setText("");
                nc6.setText("");
                p1.setText("");
                p2.setText("");

            }

            catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void t2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t2KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER) {
            String a,b,c,d,e,f;
            DefaultTableModel t=(DefaultTableModel)tb2.getModel();
            try {  Class.forName("java.sql.Driver");
                con= DriverManager.getConnection("jdbc:mysql://localhost:3306/nbank","root","123");
                stmt= con.createStatement();
                 rs=stmt.executeQuery(" select * from stmt1 where accno = '"+t2.getText()+"';");
              
                while (rs.next()) {
                    a=rs.getString("accno");
                    b=rs.getString("regno");
                    c=rs.getString("acctype");
                    d=rs.getString("amount");
                    e=rs.getString("transfer");
                    f=rs.getString("date");
                    t.addRow(new Object[]{a,b,c,d,e,f});
              
                }

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }



        }
}//GEN-LAST:event_t2KeyPressed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        int check1 = JOptionPane.showConfirmDialog(null," ARE YOU SURE YOU WANT TO CONTINUE  ");
        if(check1 == JOptionPane.YES_OPTION) {
            try {
                Class.forName("java.sql.Driver");
                 con= DriverManager.getConnection("jdbc:mysql://localhost:3306/nbank","root","123");
                 stmt= con.createStatement();

                stmt.executeUpdate("delete from stmt1 where accno = '"+t2.getText()+"';");
                JOptionPane.showMessageDialog(this, "Record is deleted");
                DefaultTableModel d=(DefaultTableModel)tb2.getModel();
                int r=d.getRowCount();
                if(r>0) {
                    for(int i=0;i<r;i++) {
                        d.removeRow(0);
                    }
                }



            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
}//GEN-LAST:event_jButton6ActionPerformed

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        changepas.setVisible(true);
           jFrame2.setVisible(false);
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        update.setBounds(0, 0, 1000, 590);
        update.setVisible(true);
           jFrame2.setVisible(false);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        new niteshlog().setVisible(true);
           jFrame2.setVisible(false);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
           new niteshad1().setVisible(true);
           jFrame2.setVisible(false);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        // TODO add your handling code here:
            new niteshdel().setVisible(true);
          jFrame2.setVisible(false);
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
          delstmt.setBounds(0, 0, 830, 500);
        delstmt.setVisible(true);

          jFrame2.setVisible(false);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseClicked
        // TODO add your handling code here:
        delstmt.dispose();

        jFrame2.setVisible(true);

    }//GEN-LAST:event_jLabel26MouseClicked

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        jFrame2.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void updateWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_updateWindowOpened
        // TODO add your handling code here:
            update.getContentPane().setBackground(Color.CYAN);
              jp1.setVisible(false);

//        c1.setVisible(false);
//            c4.setVisible(false);
//                c2.setVisible(false);
//                    c3.setVisible(false);
//                        c5.setVisible(false);

    }//GEN-LAST:event_updateWindowOpened

    private void p2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_p2KeyPressed
        // TODO add your handling code here:
        String a,b,c,d,e,f;
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
//            c1.setVisible(true);
//            c4.setVisible(true);
//                c2.setVisible(true);
//                    c3.setVisible(true);                    c5.setVisible(true);
        {
        try
        {
  Class.forName("java.sql.Driver");
  con=DriverManager.getConnection("jdbc:mysql://localhost:3306/nbank", "root", "123");
  stmt=con.createStatement();
  String o1= "Select * from account1 where regno ='"+p1.getText()+"' ;";
            System.out.println("select1");
                    rs = stmt.executeQuery(o1);
                    while(rs.next())
                    {

                    a=rs.getString("address");
                    b=rs.getString("email");
                    c=rs.getString("name");
                    d=rs.getString("age");
                    e=rs.getString("contactno");
                    
                    nc1.setText("" + a);
                    nc2.setText("" + b);
nc3.setText("" + c);
 nc4.setText("" + d);
 nc5.setText("" + e);


         System.out.println("select2");
                    }



        }
        catch(Exception ex)
        {
        JOptionPane.showMessageDialog(this, ex.getMessage());
        }

        }



    }//GEN-LAST:event_p2KeyPressed

    private void jLabel15KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel15KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel15KeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jp1.setVisible(true);


            String a,b,c,d,e,f,g,h,i,j,k;

            try {   Class.forName("java.sql.Driver");
                con= DriverManager.getConnection("jdbc:mysql://localhost:3306/nbank","root","123");
                 stmt= con.createStatement();
                 rs=stmt.executeQuery("select * from account1 where regno = '"+p1.getText()+"';");

                while (rs.next()) {
                    a=rs.getString("name");
                    b=rs.getString("address");
                    c=rs.getString("contactno");

                    f=rs.getString("email");

                    k=rs.getString("age");
                    d=rs.getString("status");




                        nc6.setText(""+a);
                        nc3.setText(""+d);

                        nc5.setText(""+c);
                        nc1.setText(""+b);
                         nc2.setText(""+f);
                           nc4.setText(""+k);





                    System.out.println("done");
}

            }
            catch (Exception ex)
            {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }


//
//               try
//        {
//        Class.forName("java.sql.Driver");
//        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/nbank", "root", "123");
//        stmt=con.createStatement();
//        String a11,b11,c11,d11,e11;
//        a11="delete from ip where class ='" +  "1"   +"'";
//        d11=" insert into ip values(  curdate() , '" +     "1"  +"'   ) ";
//        b11="Select * from ip ";
//        stmt.executeUpdate(a11);
//        stmt.executeUpdate(d11);
//         rs=stmt.executeQuery(b11);
//        while(rs.next())
//         {
//        c11=rs.getString("date");
//        nc7.setText("" +c11);
//       }
//
//        }
//        catch(Exception ex)
//        {
//
//        JOptionPane.showMessageDialog(this, ex.getMessage());
//        }



    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        update.dispose();
        jFrame2.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(niteshad1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(niteshad1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(niteshad1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(niteshad1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new niteshad1().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cb1;
    private javax.swing.JFrame changepas;
    private javax.swing.JFrame delstmt;
    private javax.swing.JTextField hint;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel jp1;
    private javax.swing.JMenuBar m1;
    private javax.swing.JTextField nc1;
    private javax.swing.JTextField nc2;
    private javax.swing.JTextField nc3;
    private javax.swing.JTextField nc4;
    private javax.swing.JTextField nc5;
    private javax.swing.JTextField nc6;
    private javax.swing.JTextField p1;
    private javax.swing.JTextField p2;
    private javax.swing.JPasswordField pw1;
    private javax.swing.JPasswordField pw2;
    private javax.swing.JPasswordField pw3;
    private javax.swing.JTextField t2;
    private javax.swing.JTable tb2;
    private javax.swing.JFrame update;
    // End of variables declaration//GEN-END:variables
}
