/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * niteshcashw.java
 *
 * Created on 12 Dec, 2014, 6:17:20 AM
 */



import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author NiteshShewaramani
 */
public class niteshcashw extends javax.swing.JFrame {

    /** Creates new form niteshcashw */
    public niteshcashw() {
        initComponents();



        try
        {
        Class.forName("java.sql.Driver");
        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/nbank", "root", "123");
        stmt=con.createStatement();
        String a,b,c,d,e;
        a="delete from ip where class ='" +  "1"   +"'";
        d=" insert into ip values(  curdate() , '" +     "1"  +"'   ) ";
        b="Select * from ip ";
        stmt.executeUpdate(a);
        stmt.executeUpdate(d);
         rs=stmt.executeQuery(b);
        while(rs.next())
         {
        c=rs.getString("date");
        x5.setText("" +c);
       }

        }
        catch(Exception ex)
        {

        JOptionPane.showMessageDialog(this, ex.getMessage());
        }






    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        x4 = new javax.swing.JTextField();
        x1 = new javax.swing.JTextField();
        x2 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        x5 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        x3 = new javax.swing.JComboBox();
        jLabel61 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(null);

        jLabel5.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 102));
        jLabel5.setText("Amount to be withdrawn");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 240, 310, 40);

        jLabel6.setFont(new java.awt.Font("Andalus", 1, 48)); // NOI18N
        jLabel6.setText("Cash Withdrawal");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(140, 10, 470, 60);

        jLabel8.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 0, 102));
        jLabel8.setText("Account No.");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(50, 90, 240, 40);

        jLabel13.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 0, 102));
        jLabel13.setText("Registration No.");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(50, 130, 190, 40);

        x4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x4ActionPerformed(evt);
            }
        });
        getContentPane().add(x4);
        x4.setBounds(360, 240, 340, 40);
        getContentPane().add(x1);
        x1.setBounds(360, 90, 340, 40);
        getContentPane().add(x2);
        x2.setBounds(360, 140, 340, 40);

        jButton6.setFont(new java.awt.Font("Andalus", 1, 36)); // NOI18N
        jButton6.setForeground(new java.awt.Color(102, 0, 102));
        jButton6.setText("Withdraw");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(180, 370, 330, 80);

        jLabel24.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(102, 0, 102));
        jLabel24.setText("Date");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(50, 300, 150, 40);
        getContentPane().add(x5);
        x5.setBounds(360, 290, 340, 40);

        jLabel27.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(102, 0, 102));
        jLabel27.setText("Account Type");
        getContentPane().add(jLabel27);
        jLabel27.setBounds(50, 180, 230, 40);

        x3.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        x3.setForeground(new java.awt.Color(102, 0, 102));
        x3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Savings Account", "Recurring Deposit", "Fixed Deposit" }));
        getContentPane().add(x3);
        x3.setBounds(360, 190, 340, 40);

        jLabel61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/B1.jpg"))); // NOI18N
        jLabel61.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel61MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel61);
        jLabel61.setBounds(30, 370, 70, 70);

        pack();
    }// </editor-fold>//GEN-END:initComponents
Connection con=null;
Statement stmt=null;
ResultSet rs=null;
    private void x4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x4ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_x4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        String a = null,b = null,c=null;
        int x,y,z;
        int check1 = JOptionPane.showConfirmDialog(null," ARE YOU SURE YOU WANT TO CONTINUE  ");
        if(check1 == JOptionPane.YES_OPTION) {
            try {
                Class.forName("java.sql.Driver");
                con= DriverManager.getConnection("jdbc:mysql://localhost:3306/nbank","root","123");
                stmt= con.createStatement();
                ResultSet rs=stmt.executeQuery(" select * from account1 where accno = '"+x1.getText()+"';");
                while (rs.next()) {
                    a=rs.getString("regno");
                    b=rs.getString("amount");
                   c=rs.getString("status");
                }
                x=Integer.parseInt(b);
                y=Integer.parseInt(x4.getText());
                z=x-y;

                if(a.equals(x2.getText())) {
                    if(z>0) {

                          if(c.equals("On"))
                          {
                        stmt.executeUpdate("insert into stmt1 values('"+x1.getText()+"','"+x2.getText()+"','"+x3.getSelectedItem()+"','"+x4.getText()+"','Withdraw','"+x5.getText()+"');");

                        JOptionPane.showMessageDialog(this, "Total Balance = "+ z);
                        stmt.executeUpdate("update account1 set amount='"+z+"' where accno='"+x1.getText()+"';");

                        JOptionPane.showMessageDialog(this, "Amount is withdrawn");
                        x1.setText("");
                        x2.setText("");
                        x4.setText("");
                          }

                               else
                         {
                               JOptionPane.showMessageDialog(this, "This Account is Blocked");
                               
                         }


                    } else {
                        JOptionPane.showMessageDialog(this, "Amount available in your account is less than needed.");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Account does not exist");
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error");
            }
        }
}//GEN-LAST:event_jButton6ActionPerformed

    private void jLabel61MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel61MouseClicked
        // TODO add your handling code here:
          new niteshuser().setVisible(true);
      this.setVisible(false);


}//GEN-LAST:event_jLabel61MouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new niteshcashw().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField x1;
    private javax.swing.JTextField x2;
    private javax.swing.JComboBox x3;
    private javax.swing.JTextField x4;
    private javax.swing.JTextField x5;
    // End of variables declaration//GEN-END:variables

}
