/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * niteshcasht.java
 *
 * Created on 12 Dec, 2014, 6:17:02 AM
 */



import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author NiteshShewaramani
 */
public class niteshcasht extends javax.swing.JFrame {

    /** Creates new form niteshcasht */
    public niteshcasht() {
        initComponents();


        try
        {
        Class.forName("java.sql.Driver");
        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/nbank", "root", "123");
        stmt=con.createStatement();
        String a,b,c,d,e;
        a="delete from ip where class ='" +  "1"   +"'";
        d=" insert into ip values(  curdate() , '" +     "1"  +"'   ) ";
        b="Select * from ip ";
        stmt.executeUpdate(a);
        stmt.executeUpdate(d);
         rs=stmt.executeQuery(b);
        while(rs.next())
         {
        c=rs.getString("date");
        z6.setText("" +c);
       }

        }
        catch(Exception ex)
        {

        JOptionPane.showMessageDialog(this, ex.getMessage());
        }



    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        z5 = new javax.swing.JTextField();
        z1 = new javax.swing.JTextField();
        z2 = new javax.swing.JTextField();
        trans = new javax.swing.JButton();
        z4 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        z6 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        z3 = new javax.swing.JComboBox();
        jLabel62 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 0, 102));
        jLabel18.setText("Amount to be Transfered");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));

        jLabel19.setFont(new java.awt.Font("Andalus", 1, 48)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(102, 0, 102));
        jLabel19.setText("Cash Transfer");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, -1, -1));

        jLabel20.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(102, 0, 102));
        jLabel20.setText("Account No. of Sender");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        jLabel21.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(102, 0, 102));
        jLabel21.setText("Registration No. of Sender");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));
        getContentPane().add(z5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 270, 40));
        getContentPane().add(z1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 270, 40));

        z2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                z2ActionPerformed(evt);
            }
        });
        getContentPane().add(z2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 270, 40));

        trans.setFont(new java.awt.Font("Andalus", 1, 36)); // NOI18N
        trans.setForeground(new java.awt.Color(102, 0, 102));
        trans.setText("Transfer");
        trans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transActionPerformed(evt);
            }
        });
        getContentPane().add(trans, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, -1, -1));
        getContentPane().add(z4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 270, 40));

        jLabel22.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(102, 0, 102));
        jLabel22.setText("Account No. of Receiver");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        jLabel25.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(102, 0, 102));
        jLabel25.setText("Date");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, -1));
        getContentPane().add(z6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 340, 270, 40));

        jLabel28.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(102, 0, 102));
        jLabel28.setText("Account Type");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        z3.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        z3.setForeground(new java.awt.Color(102, 0, 102));
        z3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Savings Account", "Recurring Deposit", "Fixed Deposit" }));
        getContentPane().add(z3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 270, -1));

        jLabel62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/B1.jpg"))); // NOI18N
        jLabel62.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel62MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
Connection con=null;
Statement stmt=null;
ResultSet rs=null;
    private void z2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_z2ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_z2ActionPerformed

    private void transActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transActionPerformed
        // TODO add your handling code here:
        String a = null,b = null,c = null, d = null,e = null,f=null;
        int x,y,z,u,v;
        int check1 = JOptionPane.showConfirmDialog(null," ARE YOU SURE YOU WANT TO CONTINUE  ");
        if(check1 == JOptionPane.YES_OPTION) {
            try {
                Class.forName("java.sql.Driver");
                con= DriverManager.getConnection("jdbc:mysql://localhost:3306/nbank","root","123");
                stmt= con.createStatement();
                rs=stmt.executeQuery(" select * from account1 where accno = '"+z1.getText()+"';");
                while (rs.next()) {
                    a=rs.getString("regno");
                    b=rs.getString("amount");
                    f=rs.getString("status");

                }
                ResultSet rs1=stmt.executeQuery(" select * from account1 where accno = '"+z4.getText()+"';");
                while (rs1.next()) {
                    c=rs1.getString("regno");
                    d=rs1.getString("amount");
                    e=rs1.getString("acctype");
                }
                x=Integer.parseInt(b);
                y=Integer.parseInt(z5.getText());
                z=x-y;
                u=Integer.parseInt(d);
                v=u+y;
                if(a.equals(z2.getText())) {
                    if(z>0) 
                    {

                        if(f.equals("On"))
                        {
                        stmt.executeUpdate("insert into stmt1 values('"+z1.getText()+"','"+z2.getText()+"','"+z3.getSelectedItem()+"','"+z5.getText()+"','Transferred','"+z6.getText()+"');");
                        stmt.executeUpdate("insert into stmt1 values('"+z4.getText()+"','"+c+"','"+e+"','"+z5.getText()+"','Received By Transfer','"+z6.getText()+"');");
                        stmt.executeUpdate("update account1 set amount='"+z+"' where accno='"+z1.getText()+"';");
                        stmt.executeUpdate("update account1 set amount='"+v+"' where accno='"+z4.getText()+"';");
                        JOptionPane.showMessageDialog(this, "Amount is Transfered");
                        z1.setText("");
                        z2.setText("");
                        z4.setText("");
                        z5.setText("");

                        }

                           else
                    {

                    JOptionPane.showMessageDialog(this, "This Account is Blocked");

                      }

                    }

                    else {
                        JOptionPane.showMessageDialog(this, "Amount needed to transfer is more than the amount available in your account");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Account does not exist");
                }
            }

            catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
}//GEN-LAST:event_transActionPerformed

    private void jLabel62MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel62MouseClicked
        // TODO add your handling code here:
          new niteshuser().setVisible(true);
      this.setVisible(false);
}//GEN-LAST:event_jLabel62MouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new niteshcasht().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JButton trans;
    private javax.swing.JTextField z1;
    private javax.swing.JTextField z2;
    private javax.swing.JComboBox z3;
    private javax.swing.JTextField z4;
    private javax.swing.JTextField z5;
    private javax.swing.JTextField z6;
    // End of variables declaration//GEN-END:variables

}
