/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * niteshdel.java
 *
 * Created on 14 Dec, 2014, 5:29:34 AM
 */


import java.awt.Color;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Nitesh Shewaramani
 */
public class niteshdel extends javax.swing.JFrame {

    /** Creates new form niteshdel */
    public niteshdel() {
        initComponents();
        p1.setVisible(false);
         this.getContentPane().setBackground(Color.CYAN);
         p1.setBackground(Color.CYAN);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        p1 = new javax.swing.JPanel();
        nt10 = new javax.swing.JTextField();
        nt3 = new javax.swing.JTextField();
        nt6 = new javax.swing.JTextField();
        nt7 = new javax.swing.JTextField();
        nt8 = new javax.swing.JTextField();
        nt9 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        nt5 = new javax.swing.JTextField();
        nt1 = new javax.swing.JTextField();
        d1 = new javax.swing.JTextField();
        d2 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(153, 204, 0));
        jButton1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jButton1.setText("SHOW DETAILS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 240, 50));

        p1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nt10.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        nt10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "E-MAIL", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Andalus", 1, 14))); // NOI18N
        nt10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nt10ActionPerformed(evt);
            }
        });
        p1.add(nt10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 450, 80));

        nt3.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        nt3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Andalus", 1, 14))); // NOI18N
        p1.add(nt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 200, 70));

        nt6.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        nt6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "AMOUNT", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Andalus", 1, 14))); // NOI18N
        p1.add(nt6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 200, 70));

        nt7.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        nt7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CONTACT NO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Andalus", 1, 14))); // NOI18N
        nt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nt7ActionPerformed(evt);
            }
        });
        p1.add(nt7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 200, 70));

        nt8.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        nt8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ACCOUNT TYPE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Andalus", 1, 14))); // NOI18N
        p1.add(nt8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 200, 70));

        nt9.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        nt9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ADDRESS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Andalus", 1, 14))); // NOI18N
        p1.add(nt9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 450, 70));

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jButton2.setText("DELETE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        p1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 253, 150, 80));

        nt5.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        nt5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "AGE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Andalus", 1, 14))); // NOI18N
        nt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nt5ActionPerformed(evt);
            }
        });
        p1.add(nt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, 200, 70));

        nt1.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        nt1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "NAME", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Andalus", 1, 14))); // NOI18N
        nt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nt1ActionPerformed(evt);
            }
        });
        p1.add(nt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 200, 70));

        getContentPane().add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 750, 390));

        d1.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        d1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "REGISTRATION.NO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Andalus", 1, 14))); // NOI18N
        d1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d1ActionPerformed(evt);
            }
        });
        getContentPane().add(d1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 200, 70));

        d2.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        d2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ACCONT.NO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Andalus", 1, 14))); // NOI18N
        d2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d2ActionPerformed(evt);
            }
        });
        getContentPane().add(d2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 200, 70));

        jButton3.setBackground(new java.awt.Color(0, 102, 153));
        jButton3.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jButton3.setText("BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 150, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents
 Connection con =null;
 ResultSet  rs= null ;
 Statement stmt=null;
    private void nt10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nt10ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_nt10ActionPerformed

    private void nt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nt1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
 p1.setVisible(true);
 
             String a = d1.getText();
            String b,c,d,e,f,g,h,i,j,k;

            try {   Class.forName("java.sql.Driver");
                con= DriverManager.getConnection("jdbc:mysql://localhost:3306/nbank","root","123");
                 stmt= con.createStatement();
                 rs=stmt.executeQuery("select * from account1 where regno = '"+d1.getText()+"';");

                while (rs.next()) {
                    a=rs.getString("name");
                    b=rs.getString("address");
                    c=rs.getString("contactno");

                    f=rs.getString("email");

                    g=rs.getString("acctype");

                    i=rs.getString("amount");
                    k=rs.getString("age");
                    j=rs.getString("dob");
             nt1.setText(""+a);
               nt3.setText(""+j);
                 nt6.setText(""+i);
                   nt7.setText(""+c);
                     nt8.setText(""+g);
                       nt9.setText(""+b);
                         nt10.setText(""+f);
                           nt5.setText(""+k);





                    System.out.println("done");
}

            }
            catch (Exception ex)
            {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nt7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nt7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         int check1 = JOptionPane.showConfirmDialog(null," ARE YOU SURE YOU WANT TO CONTINUE  ");
        if(check1 == JOptionPane.YES_OPTION) {
            try {  Class.forName("java.sql.Driver");
                 con= DriverManager.getConnection("jdbc:mysql://localhost:3306/nbank","root","123");
                 stmt= con.createStatement();

                stmt.executeUpdate("delete from account1 where regno = '"+d1.getText()+"';");
                JOptionPane.showMessageDialog(this, "record is deleted");
                nt1.setText("");
               nt3.setText("");
                 nt6.setText("");
                   nt7.setText("");
                     nt8.setText("");
                       nt9.setText("");
                         nt10.setText("");
                           nt5.setText("");
                           d1.setText("");
                           d2.setText("");
                            p1.setVisible(false);
                }



         catch (Exception ex) {
                JOptionPane.showMessageDialog(this,ex.getMessage());
            }
        }



    }//GEN-LAST:event_jButton2ActionPerformed

    private void nt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nt5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nt5ActionPerformed

    private void d1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d1ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_d1ActionPerformed

    private void d2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d2ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_d2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new niteshad1().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new niteshdel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField d1;
    private javax.swing.JTextField d2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JTextField nt1;
    private javax.swing.JTextField nt10;
    private javax.swing.JTextField nt3;
    private javax.swing.JTextField nt5;
    private javax.swing.JTextField nt6;
    private javax.swing.JTextField nt7;
    private javax.swing.JTextField nt8;
    private javax.swing.JTextField nt9;
    private javax.swing.JPanel p1;
    // End of variables declaration//GEN-END:variables

}
