/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * niteshlog.java
 *
 * Created on 6 Dec, 2014, 4:45:10 PM
 */


import java.sql.*;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nitesh Shewaramani
 */
public class niteshlog extends javax.swing.JFrame {

    /** Creates new form niteshlog */
    public niteshlog() {
        initComponents();
        t5.setVisible(false);
           t8.setVisible(false);
           fo1.setVisible(false);
           fo2.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adframe = new javax.swing.JFrame();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        t4 = new javax.swing.JPasswordField();
        jLabel15 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        t5 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        fo1 = new javax.swing.JLabel();
        userframe = new javax.swing.JFrame();
        jLabel13 = new javax.swing.JLabel();
        t6 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        t7 = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        t8 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        fo2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        admin2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        user2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        adframe.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        adframe.setBackground(new java.awt.Color(255, 255, 255));
        adframe.setMinimumSize(new java.awt.Dimension(900, 530));
        adframe.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 0, 102));
        jLabel12.setText("Username :");
        adframe.getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 79, 170, 60));

        jLabel14.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 0, 102));
        jLabel14.setText("Password :");
        adframe.getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 179, 170, 70));

        t3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3ActionPerformed(evt);
            }
        });
        adframe.getContentPane().add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 330, 60));

        t4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t4ActionPerformed(evt);
            }
        });
        adframe.getContentPane().add(t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 330, 70));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/p7.jpg"))); // NOI18N
        adframe.getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 79, 220, 215));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/log3.jpg"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jButton5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton5pasentered(evt);
            }
        });
        adframe.getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, 139, 59));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view1.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton1MouseReleased(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        adframe.getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 190, 90, 60));
        adframe.getContentPane().add(t5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 330, 70));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/url.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        adframe.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 80, 70));

        fo1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        fo1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "HINT", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 1, 18))); // NOI18N
        adframe.getContentPane().add(fo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 340, 440, 90));

        userframe.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        userframe.setBackground(new java.awt.Color(255, 255, 255));
        userframe.setMinimumSize(new java.awt.Dimension(856, 515));
        userframe.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 0, 102));
        jLabel13.setText("Username :");
        userframe.getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 150, 80));
        userframe.getContentPane().add(t6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 230, 70));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lock1.jpg"))); // NOI18N
        userframe.getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 150, 170));

        jLabel17.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 0, 102));
        jLabel17.setText("Password :");
        userframe.getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 130, 70));

        t7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t7ActionPerformed(evt);
            }
        });
        userframe.getContentPane().add(t7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 230, 70));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view1.png"))); // NOI18N
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton2MouseReleased(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        userframe.getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 200, 90, 70));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/log3.jpg"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jButton6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton6pasentered(evt);
            }
        });
        userframe.getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, 139, 60));
        userframe.getContentPane().add(t8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 230, 70));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/url.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        userframe.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 80, 70));

        fo2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        fo2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "HINT", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 1, 18))); // NOI18N
        userframe.getContentPane().add(fo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, 390, 90));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Login As -");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, -1, -1));

        admin2.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        admin2.setForeground(new java.awt.Color(255, 255, 255));
        admin2.setText("Admin");
        admin2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                admin2MouseClicked(evt);
            }
        });
        getContentPane().add(admin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, -1, -1));

        jLabel3.setFont(new java.awt.Font("Andalus", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Welcome to State Bank of India");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        user2.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        user2.setForeground(new java.awt.Color(255, 255, 255));
        user2.setText("User");
        user2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                user2MouseClicked(evt);
            }
        });
        getContentPane().add(user2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 340, -1, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/5.jpg"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 200, -1));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/4.jpg"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, 230, -1));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/p10.jpg"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 120, 200, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ip6.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents
 int wp =0;
Connection con =null;
Statement stmt=null;
ResultSet rs=null;
    private void admin2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_admin2MouseClicked
        // TODO add your handling code here:
        adframe.setVisible(true);
        this.setVisible(false);
}//GEN-LAST:event_admin2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
}//GEN-LAST:event_jLabel3MouseClicked

    private void user2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user2MouseClicked
        // TODO add your handling code here:

        userframe.setVisible(true);
        this.setVisible(false);
}//GEN-LAST:event_user2MouseClicked

    private void t3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_t3ActionPerformed

    private void t4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t4ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_t4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        // TODO add your handling code here:
        String a , b= null , c , d , e , f , g ,h , i ;
        String  a1=new String(t4.getPassword());

        try {
              Class.forName("java.sql.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/nbank","root","123");
            stmt =  con.createStatement();
            ResultSet rs=stmt.executeQuery(" select * from pas where name = '" + "admin" +"';");
            while (rs.next()) {
             
                b=rs.getString("password");


            }

            if( a1.equals(b)) //admin
            {
                niteshad1  m1 = new niteshad1();
                m1.setVisible(true);
                this.setVisible(false);
                adframe.setVisible(false);
            }

            else {
                JOptionPane.showMessageDialog(null, " YOUR PASSWORD IS INCORRECT ");

                t4.setText("");
                wp = wp + 1 ;
                if (wp==3) {
                    System.exit(0);

                }

            }


        }

        catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton5pasentered(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton5pasentered
        // TODO add your handling code here:
}//GEN-LAST:event_jButton5pasentered

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        // TODO add your handling code here:
        String  a1=new String(t4.getPassword());
        t5.setVisible(true);
        t5.setText("" + a1);
        t4.setVisible(false);
    }//GEN-LAST:event_jButton1MousePressed

    private void jButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseReleased
        // TODO add your handling code here:
        t5.setVisible(false);
        t4.setVisible(true);
}//GEN-LAST:event_jButton1MouseReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void t7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t7ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_t7ActionPerformed

    private void jButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MousePressed
        // TODO add your handling code here:
        String  a1=new String(t7.getPassword());
        t8.setVisible(true);
        t8.setText("" + a1);
        t7.setVisible(false);
    }//GEN-LAST:event_jButton2MousePressed

    private void jButton2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseReleased
        // TODO add your handling code here:
        t8.setVisible(false);
        t7.setVisible(true);
}//GEN-LAST:event_jButton2MouseReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        // TODO add your handling code here:
}//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        String a,b= null,c,d,e,f,g,h,i;
        String  a21=new String(t7.getPassword());

        try {
              Class.forName("java.sql.Driver");
            con= DriverManager.getConnection("jdbc:mysql://localhost:3306/nbank","root","123");
            stmt= con.createStatement();
            ResultSet rs=stmt.executeQuery(" select * from pas where name = '" +"user" +"';");
            while (rs.next()) {

                b=rs.getString("password");
 }


            if( a21.equals(b)) //user
            {
               new niteshuser().setVisible(true);
                this.setVisible(false);
                System.out.println("nc");
            }

            else {
                JOptionPane.showMessageDialog(null, "  YOUR PASSWORD IS INCORRECT");

                t7.setText("");
                wp = wp + 1 ;


                if (wp==3)
                {
                    System.exit(0);

                }

            }


        }

        catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }

        userframe.dispose();
}//GEN-LAST:event_jButton6ActionPerformed

    private void jButton6pasentered(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton6pasentered
        // TODO add your handling code here:
}//GEN-LAST:event_jButton6pasentered

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        fo1.setVisible(true);
int z100;
String a=null,b,c,d;
        try {
              Class.forName("java.sql.Driver");
            con= DriverManager.getConnection("jdbc:mysql://localhost:3306/nbank","root","123");
            stmt= con.createStatement();
            ResultSet rs=stmt.executeQuery(" select * from pas where name = '" +"admin" +"';");
            while (rs.next()) {
                a=rs.getString("hint");
            }
           fo1.setText("" +a);
            c=fo1.getText();
            z100=c.length();
            if(z100>=1)
            {
            fo1.setText("" +a);


            }
            else
            {
            fo1.setText("no hint given by the admin");
            }





        }

        catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }


    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
          fo2.setVisible(true);
                 int z100;
             String a=null,b,c,d;
        try
        {
              Class.forName("java.sql.Driver");
            con= DriverManager.getConnection("jdbc:mysql://localhost:3306/nbank","root","123");
            stmt= con.createStatement();
            ResultSet rs=stmt.executeQuery(" select * from pas where name = '" +"user" +"';");
            while (rs.next()) {
                a=rs.getString("hint");
            }
        z100=a.length();

      
        
            if(z100>=1)
            {
            fo2.setText("" +a);


            }
            else
            {
            fo2.setText("no hint given by the admin");
            }





        }

        catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }

    }//GEN-LAST:event_jLabel5MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         adframe.setVisible(true);

        this.setVisible(false);


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
          userframe.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        customer1 c1 = new customer1();
        c1.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jButton4ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new niteshlog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame adframe;
    private javax.swing.JLabel admin2;
    private javax.swing.JLabel fo1;
    private javax.swing.JLabel fo2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField t3;
    private javax.swing.JPasswordField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JPasswordField t7;
    private javax.swing.JTextField t8;
    private javax.swing.JLabel user2;
    private javax.swing.JFrame userframe;
    // End of variables declaration//GEN-END:variables

}
