/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * niteshcashd.java
 *
 * Created on 12 Dec, 2014, 6:16:43 AM
 */



import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author NiteshShewaramani
 */
public class niteshcashd extends javax.swing.JFrame {

    /** Creates new form niteshcashd */
    public niteshcashd() {
        initComponents();



        try
        {
        Class.forName("java.sql.Driver");
        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/nbank", "root", "123");
        stmt=con.createStatement();
        String a,b,c,d,e;
        a="delete from ip where class ='" +  "1"   +"'";
        d=" insert into ip values(  curdate() , '" +     "1"  +"'   ) ";
        b="Select * from ip ";
        stmt.executeUpdate(a);
        stmt.executeUpdate(d);
         rs=stmt.executeQuery(b);
        while(rs.next())
         {
        c=rs.getString("date");
        t5.setText("" +c);
       }

        }
        catch(Exception ex)
        {

        JOptionPane.showMessageDialog(this, ex.getMessage());
        }




    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel26 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        t3 = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        DEPOSIT = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        t5 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t1 = new javax.swing.JTextField();
        jLabel63 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(102, 0, 102));
        jLabel26.setText("Account Type");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        jLabel23.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(102, 0, 102));
        jLabel23.setText("Date");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        t3.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        t3.setForeground(new java.awt.Color(102, 0, 102));
        t3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Savings Account", "Recurring Deposit", "Fixed Deposit" }));
        t3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3ActionPerformed(evt);
            }
        });
        getContentPane().add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, 310, -1));

        jLabel12.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 0, 102));
        jLabel12.setText("Registration No.");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        DEPOSIT.setFont(new java.awt.Font("Andalus", 1, 36)); // NOI18N
        DEPOSIT.setForeground(new java.awt.Color(102, 0, 102));
        DEPOSIT.setText("DEPOSIT CASH");
        DEPOSIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DEPOSITActionPerformed(evt);
            }
        });
        getContentPane().add(DEPOSIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, -1, 60));

        jLabel11.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 0, 102));
        jLabel11.setText("Account No.");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        jLabel9.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 0, 102));
        jLabel9.setText("Amount to be deposited");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        jLabel10.setFont(new java.awt.Font("Andalus", 1, 48)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 0, 102));
        jLabel10.setText("Cash Deposit");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, -1, -1));
        getContentPane().add(t5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 310, 40));
        getContentPane().add(t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 310, 40));
        getContentPane().add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 310, 40));
        getContentPane().add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 310, 40));

        jLabel63.setIcon(new javax.swing.ImageIcon(getClass().getResource("/B1.jpg"))); // NOI18N
        jLabel63.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel63MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 90, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents
Connection con=null;
Statement stmt=null;
ResultSet rs=null;
    private void t3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_t3ActionPerformed

    private void DEPOSITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DEPOSITActionPerformed
        // TODO add your handling code here:
        int check1 = JOptionPane.showConfirmDialog(null," ARE YOU SURE YOU WANT TO CONTINUE  ");
        if(check1 == JOptionPane.YES_OPTION) {
            String a = null,b = null,c,d,e=null;
            int x,y,z;
            try {
                Class.forName("java.sql.Driver");
                con= DriverManager.getConnection("jdbc:mysql://localhost:3306/nbank","root","123");
                stmt= con.createStatement();
                rs=stmt.executeQuery(" select * from account1 where accno = '"+t1.getText()+"'");
                while (rs.next()) {
                    a=rs.getString("regno");
                    b=rs.getString("amount");
                     e=rs.getString("status");

                }
                x=Integer.parseInt(b);
                y=Integer.parseInt(t4.getText());
                z=x+y;

                if(a.equals(t2.getText())) {

                       if(e.equals("On"))
                       {
                    stmt.executeUpdate("insert into stmt1 values('"+t1.getText()+"','"+t2.getText()+"','"+t3.getSelectedItem()+"','"+t4.getText()+"', 'Deposit'  ,'"+t5.getText()+"');");

                    JOptionPane.showMessageDialog(this, "Total Balance = "+z);
                    stmt.executeUpdate("update account1 set amount='"+z+"' where accno='"+t1.getText()+"';");

                    JOptionPane.showMessageDialog(this, "Amount is Deposited");
                    t1.setText("");
                    t2.setText("");
                    t4.setText("");
                       }


                            else
                    {

                    JOptionPane.showMessageDialog(this, "This Account is Blocked");
                    }



                } else {
                    JOptionPane.showMessageDialog(this, "Account does not exist");
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
}//GEN-LAST:event_DEPOSITActionPerformed

    private void jLabel63MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel63MouseClicked
        // TODO add your handling code here:
       new niteshuser().setVisible(true);
      this.setVisible(false);

    }//GEN-LAST:event_jLabel63MouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new niteshcashd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DEPOSIT;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JComboBox t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    // End of variables declaration//GEN-END:variables

}
