/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * niteshpd.java
 *
 * Created on 12 Dec, 2014, 3:23:54 PM
 */


import java.sql.*;
import javax.swing.JOptionPane;



/**
 *
 * @author NiteshShewaramani
 */
public class niteshpd extends javax.swing.JFrame {

    /** Creates new form niteshpd */
    public niteshpd() {
        initComponents();

//this.getContentPane().setBackground(color.blue);


        try
        {
        Class.forName("java.sql.Driver");
        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/nbank", "root", "123");
        stmt=con.createStatement();
        String a,b,c,d,e;
        a="delete from ip where class ='" +  "1"   +"'";
        d=" insert into ip values(  curdate() , '" +     "1"  +"'   ) ";
        b="Select * from ip ";
        stmt.executeUpdate(a);
        stmt.executeUpdate(d);
         rs=stmt.executeQuery(b);
        while(rs.next())
         {
        c=rs.getString("date");
        ns5.setText("" +c);

       }

        }
        catch(Exception ex)
        {

        JOptionPane.showMessageDialog(this, ex.getMessage());
        }




    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        review = new javax.swing.JFrame();
        jLabel55 = new javax.swing.JLabel();
        nt2 = new javax.swing.JTextField();
        nt4 = new javax.swing.JTextField();
        nt9 = new javax.swing.JTextField();
        nt7 = new javax.swing.JTextField();
        nt10 = new javax.swing.JTextField();
        nt8 = new javax.swing.JTextField();
        nt3 = new javax.swing.JTextField();
        nt6 = new javax.swing.JTextField();
        nt5 = new javax.swing.JTextField();
        nt1 = new javax.swing.JTextField();
        jLabel57 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jFrame1 = new javax.swing.JFrame();
        jLabel59 = new javax.swing.JLabel();
        ag1 = new javax.swing.JTextField();
        jLabel60 = new javax.swing.JLabel();
        ns9 = new javax.swing.JTextField();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        rg1 = new javax.swing.JTextField();
        jLabel64 = new javax.swing.JLabel();
        ns10 = new javax.swing.JComboBox();
        jLabel65 = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        c1 = new javax.swing.JTextField();
        ns2 = new javax.swing.JTextField();
        ns3 = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        ns4 = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        ns5 = new javax.swing.JTextField();
        ns6 = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();

        review.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        review.setMinimumSize(new java.awt.Dimension(780, 600));
        review.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel55.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        jLabel55.setText("REVIEW");
        review.getContentPane().add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 110, -1));

        nt2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        nt2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ACCOUNT NO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 1, 14))); // NOI18N
        review.getContentPane().add(nt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 200, 70));

        nt4.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        nt4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "REGISTRATION NO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 1, 14))); // NOI18N
        review.getContentPane().add(nt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 200, 70));

        nt9.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        nt9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ADDRESS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 1, 14))); // NOI18N
        review.getContentPane().add(nt9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 450, 70));

        nt7.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        nt7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CONTACT NO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 1, 14))); // NOI18N
        review.getContentPane().add(nt7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 200, 70));

        nt10.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        nt10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "E-MAIL", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 1, 14))); // NOI18N
        nt10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nt10ActionPerformed(evt);
            }
        });
        review.getContentPane().add(nt10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 450, 70));

        nt8.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        nt8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ACCOUNT TYPE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 1, 14))); // NOI18N
        review.getContentPane().add(nt8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 200, 70));

        nt3.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        nt3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 1, 14))); // NOI18N
        review.getContentPane().add(nt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, 200, 70));

        nt6.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        nt6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "AMOUNT", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 1, 14))); // NOI18N
        review.getContentPane().add(nt6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, 200, 70));

        nt5.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        nt5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "AGE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 1, 14))); // NOI18N
        review.getContentPane().add(nt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 200, 70));

        nt1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        nt1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "NAME", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 1, 14))); // NOI18N
        review.getContentPane().add(nt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 200, 70));

        jLabel57.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cross2.png"))); // NOI18N
        jLabel57.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel57MouseClicked(evt);
            }
        });
        review.getContentPane().add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 490, 80, 80));

        jLabel56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tick3.jpg"))); // NOI18N
        jLabel56.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel56MouseClicked(evt);
            }
        });
        review.getContentPane().add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 490, 80, 90));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yellow.jpg"))); // NOI18N
        review.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 590));

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jFrame1.setBackground(new java.awt.Color(0, 153, 153));
        jFrame1.setMinimumSize(new java.awt.Dimension(1000, 500));
        jFrame1.getContentPane().setLayout(null);

        jLabel59.setIcon(new javax.swing.ImageIcon(getClass().getResource("/B1.jpg"))); // NOI18N
        jLabel59.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel59MouseClicked(evt);
            }
        });
        jFrame1.getContentPane().add(jLabel59);
        jLabel59.setBounds(70, 300, 70, 60);
        jFrame1.getContentPane().add(ag1);
        ag1.setBounds(240, 160, 180, 40);

        jLabel60.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(102, 0, 102));
        jLabel60.setText("Account type");
        jFrame1.getContentPane().add(jLabel60);
        jLabel60.setBounds(460, 100, 170, 40);

        ns9.setText("1000");
        jFrame1.getContentPane().add(ns9);
        ns9.setBounds(240, 230, 180, 40);

        jLabel61.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(102, 0, 102));
        jLabel61.setText("Amount");
        jFrame1.getContentPane().add(jLabel61);
        jLabel61.setBounds(50, 220, 130, 38);

        jLabel62.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(102, 0, 102));
        jLabel62.setText("Account No.");
        jFrame1.getContentPane().add(jLabel62);
        jLabel62.setBounds(50, 160, 170, 38);

        jLabel63.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FollowUp.jpg"))); // NOI18N
        jLabel63.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jFrame1.getContentPane().add(jLabel63);
        jLabel63.setBounds(460, 190, 170, 160);
        jFrame1.getContentPane().add(rg1);
        rg1.setBounds(240, 100, 180, 40);

        jLabel64.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        jLabel64.setForeground(new java.awt.Color(102, 0, 102));
        jLabel64.setText("Registration No.");
        jFrame1.getContentPane().add(jLabel64);
        jLabel64.setBounds(50, 100, 230, 40);

        ns10.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        ns10.setForeground(new java.awt.Color(102, 0, 102));
        ns10.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Savings Account", "Recurring Deposit", "Fixed Deposit" }));
        jFrame1.getContentPane().add(ns10);
        ns10.setBounds(460, 140, 350, 40);

        jLabel65.setFont(new java.awt.Font("Andalus", 0, 48)); // NOI18N
        jLabel65.setForeground(new java.awt.Color(102, 0, 102));
        jLabel65.setText("Account Details");
        jFrame1.getContentPane().add(jLabel65);
        jLabel65.setBounds(360, 10, 400, 70);

        submit.setBackground(new java.awt.Color(51, 51, 51));
        submit.setFont(new java.awt.Font("Andalus", 1, 36)); // NOI18N
        submit.setForeground(new java.awt.Color(0, 255, 0));
        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(submit);
        submit.setBounds(240, 300, 190, 60);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ip71.jpg"))); // NOI18N
        jFrame1.getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 840, 430);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1100, 445));
        getContentPane().setLayout(null);

        jLabel40.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(102, 0, 102));
        jLabel40.setText("Name");
        getContentPane().add(jLabel40);
        jLabel40.setBounds(70, 80, 70, 40);

        jLabel41.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(102, 0, 102));
        jLabel41.setText("Address");
        getContentPane().add(jLabel41);
        jLabel41.setBounds(70, 140, 140, 40);

        jLabel42.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(102, 0, 102));
        jLabel42.setText("Contact No.");
        getContentPane().add(jLabel42);
        jLabel42.setBounds(70, 200, 160, 40);
        getContentPane().add(c1);
        c1.setBounds(260, 80, 290, 40);
        getContentPane().add(ns2);
        ns2.setBounds(260, 140, 290, 40);
        getContentPane().add(ns3);
        ns3.setBounds(260, 200, 290, 40);

        jLabel43.setFont(new java.awt.Font("Andalus", 0, 48)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(102, 0, 102));
        jLabel43.setText("Personal Details");
        getContentPane().add(jLabel43);
        jLabel43.setBounds(370, 0, 400, 70);
        getContentPane().add(ns4);
        ns4.setBounds(260, 260, 290, 40);

        jLabel44.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(102, 0, 102));
        jLabel44.setText("Email Id");
        getContentPane().add(jLabel44);
        jLabel44.setBounds(70, 270, 140, 40);

        jLabel45.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(102, 0, 102));
        jLabel45.setText("Date ");
        getContentPane().add(jLabel45);
        jLabel45.setBounds(610, 84, 150, 30);

        jLabel46.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(102, 0, 102));
        jLabel46.setText("Age");
        getContentPane().add(jLabel46);
        jLabel46.setBounds(610, 130, 80, 38);
        getContentPane().add(ns5);
        ns5.setBounds(770, 80, 210, 40);
        getContentPane().add(ns6);
        ns6.setBounds(770, 130, 210, 40);

        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/F1.jpg"))); // NOI18N
        jLabel47.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel47MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel47);
        jLabel47.setBounds(590, 230, 70, 70);

        jLabel58.setIcon(new javax.swing.ImageIcon(getClass().getResource("/B1.jpg"))); // NOI18N
        jLabel58.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel58MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel58);
        jLabel58.setBounds(70, 320, 70, 60);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel47MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel47MouseClicked
        // TODO add your handling code here:


        String a,b;
        a=c1.getText();
        int c11 =a.length();
        int c12 =ns2.getText().length() ;
        int c13 =ns3.getText().length() ;

        if(c11<1) {
            JOptionPane.showMessageDialog(this,"pls enter name");

        }




        else {
      jFrame1.setVisible(true);
      jFrame1.setBounds(0, 0, 850, 400);


            try {

                Class.forName("java.sql.Driver");
                con= DriverManager.getConnection("jdbc:mysql://localhost:3306/nbank","root","123");
                stmt= con.createStatement();
                rs=stmt.executeQuery(" select * from reg where class='"+ 12 +"';");
                while (rs.next()) {
                    String a12 =  rs.getString("regno");
                    String a13 =  rs.getString("acno");

                    rg1.setText("" + a12);
                    ag1.setText("" + a13);
                }
            }


            catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }



            int a21 = Integer.parseInt(rg1.getText());
            int   a22 ;
            a22 = a21 + 1;
            int a221 = Integer.parseInt(ag1.getText());
            int   a222 ;
            a222 = a221 + 1;


            try

            {
                Class.forName("java.sql.Driver");
                con= DriverManager.getConnection("jdbc:mysql://localhost:3306/nbank","root","123");
                stmt= con.createStatement();
                String k ="Update reg set regno='"+ a22 +"' ,acno='"+  a222 +"'  where class='" + 12 + "'" ;
                stmt.executeUpdate(k);
            }
            catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }

            this.setVisible(false);
        }
}//GEN-LAST:event_jLabel47MouseClicked

    private void jLabel58MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel58MouseClicked
        // TODO add your handling code here:
        new niteshuser().setVisible(true);
       this.setVisible(false);
}//GEN-LAST:event_jLabel58MouseClicked

    private void nt10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nt10ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_nt10ActionPerformed

    private void jLabel56MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel56MouseClicked


        
                int check1 = JOptionPane.showConfirmDialog(null," ARE YOU SURE YOU WANT TO CREATE ACCOUNT  ");
                if(check1 == JOptionPane.YES_OPTION) {
        
                    try
        
                    {
                        Class.forName("java.sql.Driver");
                        con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/nbank","root","123");
                        stmt=(Statement) con.createStatement();
                        String nick = "insert into account1 values('"+nt1.getText()+"','"+nt9.getText()+"','"+nt7.getText()+"','"+nt4.getText()+"','"+nt10.getText()+"','"+nt8.getText()+"','"+nt2.getText()+"','"+nt6.getText()+"','"+nt5.getText()+"','"+nt3.getText()+"' ,'" + "On" + "' )";


           stmt.executeUpdate(nick);


        
                        JOptionPane.showMessageDialog(this, "Account is created");

                        nt1.setText("");
                          nt2.setText("");
                            nt3.setText("");
                              nt4.setText("");
                                nt5.setText("");
                                  nt6.setText("");
                                    nt7.setText("");
                                      nt8.setText("");
                                        nt9.setText("");
                                          nt10.setText("");

                    }
        
                    catch (Exception ex) {
                        JOptionPane.showMessageDialog(this, ex.getMessage());
                    }
         review.dispose();
         new niteshpd().setVisible(true);
                }
}//GEN-LAST:event_jLabel56MouseClicked

    private void jLabel57MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel57MouseClicked
        // TODO add your handling code here:
               review.dispose();
        new niteshpd().setVisible(true);


                c1.setText("");  ns2.setText("");  ns3.setText("");  ns4.setText("");  ns6.setText("");
                rg1.setText("");     ns9.setText("1000");   ag1.setText("");


}//GEN-LAST:event_jLabel57MouseClicked

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
      review.setVisible(true);
      review.setBounds(0,0,780, 600);
      String b1,b2,b3,b4,b5,b6,b7,b8,b9,b10;
      nt1.setText("" + c1.getText());
      nt9.setText("" + ns2.getText());
      nt7.setText("" + ns3.getText());
      nt10.setText("" + ns4.getText());
      nt3.setText("" + ns5.getText());
      nt5.setText("" + ns6.getText());
      nt4.setText("" + rg1.getText());
      nt2.setText("" + ag1.getText());
      nt6.setText("" + ns9.getText());
      nt8.setText("" + ns10.getSelectedItem());

      jFrame1.dispose();


}//GEN-LAST:event_submitActionPerformed

    private void jLabel59MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel59MouseClicked
        // TODO add your handling code here:
        jFrame1.dispose();
        new niteshpd().setVisible(true);


    }//GEN-LAST:event_jLabel59MouseClicked
Connection con=null;
Statement stmt=null;
ResultSet rs=null;


    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new niteshpd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ag1;
    private javax.swing.JTextField c1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JComboBox ns10;
    private javax.swing.JTextField ns2;
    private javax.swing.JTextField ns3;
    private javax.swing.JTextField ns4;
    private javax.swing.JTextField ns5;
    private javax.swing.JTextField ns6;
    private javax.swing.JTextField ns9;
    private javax.swing.JTextField nt1;
    private javax.swing.JTextField nt10;
    private javax.swing.JTextField nt2;
    private javax.swing.JTextField nt3;
    private javax.swing.JTextField nt4;
    private javax.swing.JTextField nt5;
    private javax.swing.JTextField nt6;
    private javax.swing.JTextField nt7;
    private javax.swing.JTextField nt8;
    private javax.swing.JTextField nt9;
    private javax.swing.JFrame review;
    private javax.swing.JTextField rg1;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables

}
